// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/apply_agent_diff_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum agent.v1.AppliedAgentChange_ChangeType
 */
export enum AppliedAgentChange_ChangeType {
  /**
   * @generated from enum value: CHANGE_TYPE_UNSPECIFIED = 0;
   */
  CHANGE_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHANGE_TYPE_CREATED = 1;
   */
  CHANGE_TYPE_CREATED = 1,

  /**
   * @generated from enum value: CHANGE_TYPE_MODIFIED = 2;
   */
  CHANGE_TYPE_MODIFIED = 2,

  /**
   * @generated from enum value: CHANGE_TYPE_DELETED = 3;
   */
  CHANGE_TYPE_DELETED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AppliedAgentChange_ChangeType)
proto3.util.setEnumType(AppliedAgentChange_ChangeType, "agent.v1.AppliedAgentChange_ChangeType", [
  { no: 0, name: "CHANGE_TYPE_UNSPECIFIED" },
  { no: 1, name: "CHANGE_TYPE_CREATED" },
  { no: 2, name: "CHANGE_TYPE_MODIFIED" },
  { no: 3, name: "CHANGE_TYPE_DELETED" },
]);

/**
 * @generated from message agent.v1.ApplyAgentDiffToolCall
 */
export class ApplyAgentDiffToolCall extends Message<ApplyAgentDiffToolCall> {
  /**
   * @generated from field: agent.v1.ApplyAgentDiffArgs args = 1;
   */
  args?: ApplyAgentDiffArgs;

  /**
   * @generated from field: agent.v1.ApplyAgentDiffResult result = 2;
   */
  result?: ApplyAgentDiffResult;

  constructor(data?: PartialMessage<ApplyAgentDiffToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ApplyAgentDiffToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ApplyAgentDiffArgs },
    { no: 2, name: "result", kind: "message", T: ApplyAgentDiffResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplyAgentDiffToolCall {
    return new ApplyAgentDiffToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplyAgentDiffToolCall {
    return new ApplyAgentDiffToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplyAgentDiffToolCall {
    return new ApplyAgentDiffToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: ApplyAgentDiffToolCall | PlainMessage<ApplyAgentDiffToolCall> | undefined, b: ApplyAgentDiffToolCall | PlainMessage<ApplyAgentDiffToolCall> | undefined): boolean {
    return proto3.util.equals(ApplyAgentDiffToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.ApplyAgentDiffArgs
 */
export class ApplyAgentDiffArgs extends Message<ApplyAgentDiffArgs> {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId = "";

  constructor(data?: PartialMessage<ApplyAgentDiffArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ApplyAgentDiffArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplyAgentDiffArgs {
    return new ApplyAgentDiffArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplyAgentDiffArgs {
    return new ApplyAgentDiffArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplyAgentDiffArgs {
    return new ApplyAgentDiffArgs().fromJsonString(jsonString, options);
  }

  static equals(a: ApplyAgentDiffArgs | PlainMessage<ApplyAgentDiffArgs> | undefined, b: ApplyAgentDiffArgs | PlainMessage<ApplyAgentDiffArgs> | undefined): boolean {
    return proto3.util.equals(ApplyAgentDiffArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.ApplyAgentDiffResult
 */
export class ApplyAgentDiffResult extends Message<ApplyAgentDiffResult> {
  /**
   * @generated from oneof agent.v1.ApplyAgentDiffResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ApplyAgentDiffSuccess success = 1;
     */
    value: ApplyAgentDiffSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.ApplyAgentDiffError error = 2;
     */
    value: ApplyAgentDiffError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ApplyAgentDiffResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ApplyAgentDiffResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: ApplyAgentDiffSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: ApplyAgentDiffError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplyAgentDiffResult {
    return new ApplyAgentDiffResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplyAgentDiffResult {
    return new ApplyAgentDiffResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplyAgentDiffResult {
    return new ApplyAgentDiffResult().fromJsonString(jsonString, options);
  }

  static equals(a: ApplyAgentDiffResult | PlainMessage<ApplyAgentDiffResult> | undefined, b: ApplyAgentDiffResult | PlainMessage<ApplyAgentDiffResult> | undefined): boolean {
    return proto3.util.equals(ApplyAgentDiffResult, a, b);
  }
}

/**
 * @generated from message agent.v1.ApplyAgentDiffSuccess
 */
export class ApplyAgentDiffSuccess extends Message<ApplyAgentDiffSuccess> {
  /**
   * @generated from field: repeated agent.v1.AppliedAgentChange applied_changes = 1;
   */
  appliedChanges: AppliedAgentChange[] = [];

  constructor(data?: PartialMessage<ApplyAgentDiffSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ApplyAgentDiffSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "applied_changes", kind: "message", T: AppliedAgentChange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplyAgentDiffSuccess {
    return new ApplyAgentDiffSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplyAgentDiffSuccess {
    return new ApplyAgentDiffSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplyAgentDiffSuccess {
    return new ApplyAgentDiffSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: ApplyAgentDiffSuccess | PlainMessage<ApplyAgentDiffSuccess> | undefined, b: ApplyAgentDiffSuccess | PlainMessage<ApplyAgentDiffSuccess> | undefined): boolean {
    return proto3.util.equals(ApplyAgentDiffSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.AppliedAgentChange
 */
export class AppliedAgentChange extends Message<AppliedAgentChange> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: agent.v1.AppliedAgentChange_ChangeType change_type = 2;
   */
  changeType = AppliedAgentChange_ChangeType.CHANGE_TYPE_UNSPECIFIED;

  /**
   * @generated from field: optional string before_content = 3;
   */
  beforeContent?: string;

  /**
   * @generated from field: optional string after_content = 4;
   */
  afterContent?: string;

  /**
   * @generated from field: optional string error = 5;
   */
  error?: string;

  /**
   * @generated from field: optional string message_for_model = 6;
   */
  messageForModel?: string;

  constructor(data?: PartialMessage<AppliedAgentChange>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AppliedAgentChange";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "change_type", kind: "enum", T: proto3.getEnumType(AppliedAgentChange_ChangeType) },
    { no: 3, name: "before_content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "after_content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "message_for_model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AppliedAgentChange {
    return new AppliedAgentChange().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AppliedAgentChange {
    return new AppliedAgentChange().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AppliedAgentChange {
    return new AppliedAgentChange().fromJsonString(jsonString, options);
  }

  static equals(a: AppliedAgentChange | PlainMessage<AppliedAgentChange> | undefined, b: AppliedAgentChange | PlainMessage<AppliedAgentChange> | undefined): boolean {
    return proto3.util.equals(AppliedAgentChange, a, b);
  }
}

/**
 * @generated from message agent.v1.ApplyAgentDiffError
 */
export class ApplyAgentDiffError extends Message<ApplyAgentDiffError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  /**
   * @generated from field: repeated agent.v1.AppliedAgentChange applied_changes = 2;
   */
  appliedChanges: AppliedAgentChange[] = [];

  constructor(data?: PartialMessage<ApplyAgentDiffError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ApplyAgentDiffError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "applied_changes", kind: "message", T: AppliedAgentChange, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplyAgentDiffError {
    return new ApplyAgentDiffError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplyAgentDiffError {
    return new ApplyAgentDiffError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplyAgentDiffError {
    return new ApplyAgentDiffError().fromJsonString(jsonString, options);
  }

  static equals(a: ApplyAgentDiffError | PlainMessage<ApplyAgentDiffError> | undefined, b: ApplyAgentDiffError | PlainMessage<ApplyAgentDiffError> | undefined): boolean {
    return proto3.util.equals(ApplyAgentDiffError, a, b);
  }
}

