// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/ask_question_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.AskQuestionToolCall
 */
export class AskQuestionToolCall extends Message<AskQuestionToolCall> {
  /**
   * @generated from field: agent.v1.AskQuestionArgs args = 1;
   */
  args?: AskQuestionArgs;

  /**
   * @generated from field: agent.v1.AskQuestionResult result = 2;
   */
  result?: AskQuestionResult;

  constructor(data?: PartialMessage<AskQuestionToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: AskQuestionArgs },
    { no: 2, name: "result", kind: "message", T: AskQuestionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionToolCall {
    return new AskQuestionToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionToolCall {
    return new AskQuestionToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionToolCall {
    return new AskQuestionToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionToolCall | PlainMessage<AskQuestionToolCall> | undefined, b: AskQuestionToolCall | PlainMessage<AskQuestionToolCall> | undefined): boolean {
    return proto3.util.equals(AskQuestionToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionArgs
 */
export class AskQuestionArgs extends Message<AskQuestionArgs> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: repeated agent.v1.AskQuestionArgs_Question questions = 2;
   */
  questions: AskQuestionArgs_Question[] = [];

  /**
   * @generated from field: bool run_async = 5;
   */
  runAsync = false;

  /**
   * @generated from field: string async_original_tool_call_id = 6;
   */
  asyncOriginalToolCallId = "";

  constructor(data?: PartialMessage<AskQuestionArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "questions", kind: "message", T: AskQuestionArgs_Question, repeated: true },
    { no: 5, name: "run_async", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "async_original_tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionArgs {
    return new AskQuestionArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionArgs {
    return new AskQuestionArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionArgs {
    return new AskQuestionArgs().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionArgs | PlainMessage<AskQuestionArgs> | undefined, b: AskQuestionArgs | PlainMessage<AskQuestionArgs> | undefined): boolean {
    return proto3.util.equals(AskQuestionArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionArgs_Question
 */
export class AskQuestionArgs_Question extends Message<AskQuestionArgs_Question> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string prompt = 2;
   */
  prompt = "";

  /**
   * @generated from field: repeated agent.v1.AskQuestionArgs_Option options = 3;
   */
  options: AskQuestionArgs_Option[] = [];

  /**
   * @generated from field: bool allow_multiple = 4;
   */
  allowMultiple = false;

  constructor(data?: PartialMessage<AskQuestionArgs_Question>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionArgs_Question";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "options", kind: "message", T: AskQuestionArgs_Option, repeated: true },
    { no: 4, name: "allow_multiple", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionArgs_Question {
    return new AskQuestionArgs_Question().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionArgs_Question {
    return new AskQuestionArgs_Question().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionArgs_Question {
    return new AskQuestionArgs_Question().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionArgs_Question | PlainMessage<AskQuestionArgs_Question> | undefined, b: AskQuestionArgs_Question | PlainMessage<AskQuestionArgs_Question> | undefined): boolean {
    return proto3.util.equals(AskQuestionArgs_Question, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionArgs_Option
 */
export class AskQuestionArgs_Option extends Message<AskQuestionArgs_Option> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string label = 2;
   */
  label = "";

  constructor(data?: PartialMessage<AskQuestionArgs_Option>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionArgs_Option";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionArgs_Option {
    return new AskQuestionArgs_Option().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionArgs_Option {
    return new AskQuestionArgs_Option().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionArgs_Option {
    return new AskQuestionArgs_Option().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionArgs_Option | PlainMessage<AskQuestionArgs_Option> | undefined, b: AskQuestionArgs_Option | PlainMessage<AskQuestionArgs_Option> | undefined): boolean {
    return proto3.util.equals(AskQuestionArgs_Option, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionAsync
 */
export class AskQuestionAsync extends Message<AskQuestionAsync> {
  constructor(data?: PartialMessage<AskQuestionAsync>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionAsync";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionAsync {
    return new AskQuestionAsync().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionAsync {
    return new AskQuestionAsync().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionAsync {
    return new AskQuestionAsync().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionAsync | PlainMessage<AskQuestionAsync> | undefined, b: AskQuestionAsync | PlainMessage<AskQuestionAsync> | undefined): boolean {
    return proto3.util.equals(AskQuestionAsync, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionResult
 */
export class AskQuestionResult extends Message<AskQuestionResult> {
  /**
   * @generated from oneof agent.v1.AskQuestionResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.AskQuestionSuccess success = 1;
     */
    value: AskQuestionSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.AskQuestionError error = 2;
     */
    value: AskQuestionError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.AskQuestionRejected rejected = 3;
     */
    value: AskQuestionRejected;
    case: "rejected";
  } | {
    /**
     * @generated from field: agent.v1.AskQuestionAsync async = 4;
     */
    value: AskQuestionAsync;
    case: "async";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<AskQuestionResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: AskQuestionSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: AskQuestionError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: AskQuestionRejected, oneof: "result" },
    { no: 4, name: "async", kind: "message", T: AskQuestionAsync, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionResult {
    return new AskQuestionResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionResult {
    return new AskQuestionResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionResult {
    return new AskQuestionResult().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionResult | PlainMessage<AskQuestionResult> | undefined, b: AskQuestionResult | PlainMessage<AskQuestionResult> | undefined): boolean {
    return proto3.util.equals(AskQuestionResult, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionSuccess
 */
export class AskQuestionSuccess extends Message<AskQuestionSuccess> {
  /**
   * @generated from field: repeated agent.v1.AskQuestionSuccess_Answer answers = 1;
   */
  answers: AskQuestionSuccess_Answer[] = [];

  constructor(data?: PartialMessage<AskQuestionSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "answers", kind: "message", T: AskQuestionSuccess_Answer, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionSuccess {
    return new AskQuestionSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionSuccess {
    return new AskQuestionSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionSuccess {
    return new AskQuestionSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionSuccess | PlainMessage<AskQuestionSuccess> | undefined, b: AskQuestionSuccess | PlainMessage<AskQuestionSuccess> | undefined): boolean {
    return proto3.util.equals(AskQuestionSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionSuccess_Answer
 */
export class AskQuestionSuccess_Answer extends Message<AskQuestionSuccess_Answer> {
  /**
   * @generated from field: string question_id = 1;
   */
  questionId = "";

  /**
   * @generated from field: repeated string selected_option_ids = 2;
   */
  selectedOptionIds: string[] = [];

  /**
   * @generated from field: string freeform_text = 3;
   */
  freeformText = "";

  constructor(data?: PartialMessage<AskQuestionSuccess_Answer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionSuccess_Answer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "question_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "selected_option_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "freeform_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionSuccess_Answer {
    return new AskQuestionSuccess_Answer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionSuccess_Answer {
    return new AskQuestionSuccess_Answer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionSuccess_Answer {
    return new AskQuestionSuccess_Answer().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionSuccess_Answer | PlainMessage<AskQuestionSuccess_Answer> | undefined, b: AskQuestionSuccess_Answer | PlainMessage<AskQuestionSuccess_Answer> | undefined): boolean {
    return proto3.util.equals(AskQuestionSuccess_Answer, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionError
 */
export class AskQuestionError extends Message<AskQuestionError> {
  /**
   * @generated from field: string error_message = 1;
   */
  errorMessage = "";

  constructor(data?: PartialMessage<AskQuestionError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionError {
    return new AskQuestionError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionError {
    return new AskQuestionError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionError {
    return new AskQuestionError().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionError | PlainMessage<AskQuestionError> | undefined, b: AskQuestionError | PlainMessage<AskQuestionError> | undefined): boolean {
    return proto3.util.equals(AskQuestionError, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionRejected
 */
export class AskQuestionRejected extends Message<AskQuestionRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<AskQuestionRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionRejected {
    return new AskQuestionRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionRejected {
    return new AskQuestionRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionRejected {
    return new AskQuestionRejected().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionRejected | PlainMessage<AskQuestionRejected> | undefined, b: AskQuestionRejected | PlainMessage<AskQuestionRejected> | undefined): boolean {
    return proto3.util.equals(AskQuestionRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionInteractionQuery
 */
export class AskQuestionInteractionQuery extends Message<AskQuestionInteractionQuery> {
  /**
   * @generated from field: agent.v1.AskQuestionArgs args = 1;
   */
  args?: AskQuestionArgs;

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<AskQuestionInteractionQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionInteractionQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: AskQuestionArgs },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionInteractionQuery {
    return new AskQuestionInteractionQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionInteractionQuery {
    return new AskQuestionInteractionQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionInteractionQuery {
    return new AskQuestionInteractionQuery().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionInteractionQuery | PlainMessage<AskQuestionInteractionQuery> | undefined, b: AskQuestionInteractionQuery | PlainMessage<AskQuestionInteractionQuery> | undefined): boolean {
    return proto3.util.equals(AskQuestionInteractionQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.AskQuestionInteractionResponse
 */
export class AskQuestionInteractionResponse extends Message<AskQuestionInteractionResponse> {
  /**
   * @generated from field: agent.v1.AskQuestionResult result = 1;
   */
  result?: AskQuestionResult;

  constructor(data?: PartialMessage<AskQuestionInteractionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AskQuestionInteractionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "message", T: AskQuestionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskQuestionInteractionResponse {
    return new AskQuestionInteractionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskQuestionInteractionResponse {
    return new AskQuestionInteractionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskQuestionInteractionResponse {
    return new AskQuestionInteractionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AskQuestionInteractionResponse | PlainMessage<AskQuestionInteractionResponse> | undefined, b: AskQuestionInteractionResponse | PlainMessage<AskQuestionInteractionResponse> | undefined): boolean {
    return proto3.util.equals(AskQuestionInteractionResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.AsyncAskQuestionCompletionAction
 */
export class AsyncAskQuestionCompletionAction extends Message<AsyncAskQuestionCompletionAction> {
  /**
   * @generated from field: string original_tool_call_id = 1;
   */
  originalToolCallId = "";

  /**
   * @generated from field: agent.v1.AskQuestionArgs original_args = 2;
   */
  originalArgs?: AskQuestionArgs;

  /**
   * @generated from field: agent.v1.AskQuestionResult result = 3;
   */
  result?: AskQuestionResult;

  constructor(data?: PartialMessage<AsyncAskQuestionCompletionAction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.AsyncAskQuestionCompletionAction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "original_tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "original_args", kind: "message", T: AskQuestionArgs },
    { no: 3, name: "result", kind: "message", T: AskQuestionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AsyncAskQuestionCompletionAction {
    return new AsyncAskQuestionCompletionAction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AsyncAskQuestionCompletionAction {
    return new AsyncAskQuestionCompletionAction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AsyncAskQuestionCompletionAction {
    return new AsyncAskQuestionCompletionAction().fromJsonString(jsonString, options);
  }

  static equals(a: AsyncAskQuestionCompletionAction | PlainMessage<AsyncAskQuestionCompletionAction> | undefined, b: AsyncAskQuestionCompletionAction | PlainMessage<AsyncAskQuestionCompletionAction> | undefined): boolean {
    return proto3.util.equals(AsyncAskQuestionCompletionAction, a, b);
  }
}

