// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/background_shell_exec.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ShellCommandParsingResult, ShellPermissionDenied, ShellRejected } from "./shell_exec_pb.js";
import { SandboxPolicy } from "./sandbox_pb.js";

/**
 * @generated from message agent.v1.BackgroundShellSpawnArgs
 */
export class BackgroundShellSpawnArgs extends Message<BackgroundShellSpawnArgs> {
  /**
   * @generated from field: string command = 1;
   */
  command = "";

  /**
   * @generated from field: string working_directory = 2;
   */
  workingDirectory = "";

  /**
   * @generated from field: string tool_call_id = 3;
   */
  toolCallId = "";

  /**
   * @generated from field: agent.v1.ShellCommandParsingResult parsing_result = 4;
   */
  parsingResult?: ShellCommandParsingResult;

  /**
   * @generated from field: optional agent.v1.SandboxPolicy sandbox_policy = 5;
   */
  sandboxPolicy?: SandboxPolicy;

  /**
   * @generated from field: bool enable_write_shell_stdin_tool = 6;
   */
  enableWriteShellStdinTool = false;

  constructor(data?: PartialMessage<BackgroundShellSpawnArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.BackgroundShellSpawnArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "working_directory", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "parsing_result", kind: "message", T: ShellCommandParsingResult },
    { no: 5, name: "sandbox_policy", kind: "message", T: SandboxPolicy, opt: true },
    { no: 6, name: "enable_write_shell_stdin_tool", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundShellSpawnArgs {
    return new BackgroundShellSpawnArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundShellSpawnArgs {
    return new BackgroundShellSpawnArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundShellSpawnArgs {
    return new BackgroundShellSpawnArgs().fromJsonString(jsonString, options);
  }

  static equals(a: BackgroundShellSpawnArgs | PlainMessage<BackgroundShellSpawnArgs> | undefined, b: BackgroundShellSpawnArgs | PlainMessage<BackgroundShellSpawnArgs> | undefined): boolean {
    return proto3.util.equals(BackgroundShellSpawnArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.BackgroundShellSpawnResult
 */
export class BackgroundShellSpawnResult extends Message<BackgroundShellSpawnResult> {
  /**
   * @generated from oneof agent.v1.BackgroundShellSpawnResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.BackgroundShellSpawnSuccess success = 1;
     */
    value: BackgroundShellSpawnSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.BackgroundShellSpawnError error = 2;
     */
    value: BackgroundShellSpawnError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.ShellRejected rejected = 3;
     */
    value: ShellRejected;
    case: "rejected";
  } | {
    /**
     * @generated from field: agent.v1.ShellPermissionDenied permission_denied = 4;
     */
    value: ShellPermissionDenied;
    case: "permissionDenied";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<BackgroundShellSpawnResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.BackgroundShellSpawnResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: BackgroundShellSpawnSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: BackgroundShellSpawnError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: ShellRejected, oneof: "result" },
    { no: 4, name: "permission_denied", kind: "message", T: ShellPermissionDenied, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundShellSpawnResult {
    return new BackgroundShellSpawnResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundShellSpawnResult {
    return new BackgroundShellSpawnResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundShellSpawnResult {
    return new BackgroundShellSpawnResult().fromJsonString(jsonString, options);
  }

  static equals(a: BackgroundShellSpawnResult | PlainMessage<BackgroundShellSpawnResult> | undefined, b: BackgroundShellSpawnResult | PlainMessage<BackgroundShellSpawnResult> | undefined): boolean {
    return proto3.util.equals(BackgroundShellSpawnResult, a, b);
  }
}

/**
 * @generated from message agent.v1.BackgroundShellSpawnSuccess
 */
export class BackgroundShellSpawnSuccess extends Message<BackgroundShellSpawnSuccess> {
  /**
   * @generated from field: uint32 shell_id = 1;
   */
  shellId = 0;

  /**
   * @generated from field: string command = 2;
   */
  command = "";

  /**
   * @generated from field: string working_directory = 3;
   */
  workingDirectory = "";

  /**
   * @generated from field: optional uint32 pid = 4;
   */
  pid?: number;

  constructor(data?: PartialMessage<BackgroundShellSpawnSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.BackgroundShellSpawnSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shell_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "working_directory", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "pid", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundShellSpawnSuccess {
    return new BackgroundShellSpawnSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundShellSpawnSuccess {
    return new BackgroundShellSpawnSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundShellSpawnSuccess {
    return new BackgroundShellSpawnSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: BackgroundShellSpawnSuccess | PlainMessage<BackgroundShellSpawnSuccess> | undefined, b: BackgroundShellSpawnSuccess | PlainMessage<BackgroundShellSpawnSuccess> | undefined): boolean {
    return proto3.util.equals(BackgroundShellSpawnSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.BackgroundShellSpawnError
 */
export class BackgroundShellSpawnError extends Message<BackgroundShellSpawnError> {
  /**
   * @generated from field: string command = 1;
   */
  command = "";

  /**
   * @generated from field: string working_directory = 2;
   */
  workingDirectory = "";

  /**
   * @generated from field: string error = 3;
   */
  error = "";

  constructor(data?: PartialMessage<BackgroundShellSpawnError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.BackgroundShellSpawnError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "working_directory", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundShellSpawnError {
    return new BackgroundShellSpawnError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundShellSpawnError {
    return new BackgroundShellSpawnError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundShellSpawnError {
    return new BackgroundShellSpawnError().fromJsonString(jsonString, options);
  }

  static equals(a: BackgroundShellSpawnError | PlainMessage<BackgroundShellSpawnError> | undefined, b: BackgroundShellSpawnError | PlainMessage<BackgroundShellSpawnError> | undefined): boolean {
    return proto3.util.equals(BackgroundShellSpawnError, a, b);
  }
}

