// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file agent/v1/control_service.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMcpRefreshTokensRequest, GetMcpRefreshTokensResponse, GetWorkspaceChangesHashRequest, GetWorkspaceChangesHashResponse, ListArtifactsRequest, ListArtifactsResponse, ReadBinaryFileRequest, ReadBinaryFileResponse, ReadTextFileRequest, ReadTextFileResponse, RefreshGithubAccessTokenRequest, RefreshGithubAccessTokenResponse, UpdateEnvironmentVariablesRequest, UpdateEnvironmentVariablesResponse, UploadArtifactsRequest, UploadArtifactsResponse, WarmRemoteAccessServerRequest, WarmRemoteAccessServerResponse, WriteBinaryFileRequest, WriteBinaryFileResponse, WriteTextFileRequest, WriteTextFileResponse } from "./control_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Empty } from "./agent_pb.js";

/**
 * @generated from service agent.v1.ControlService
 */
export const ControlService = {
  typeName: "agent.v1.ControlService",
  methods: {
    /**
     * @generated from rpc agent.v1.ControlService.ReadTextFile
     */
    readTextFile: {
      name: "ReadTextFile",
      I: ReadTextFileRequest,
      O: ReadTextFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.WriteTextFile
     */
    writeTextFile: {
      name: "WriteTextFile",
      I: WriteTextFileRequest,
      O: WriteTextFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.ReadBinaryFile
     */
    readBinaryFile: {
      name: "ReadBinaryFile",
      I: ReadBinaryFileRequest,
      O: ReadBinaryFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.WriteBinaryFile
     */
    writeBinaryFile: {
      name: "WriteBinaryFile",
      I: WriteBinaryFileRequest,
      O: WriteBinaryFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.GetWorkspaceChangesHash
     */
    getWorkspaceChangesHash: {
      name: "GetWorkspaceChangesHash",
      I: GetWorkspaceChangesHashRequest,
      O: GetWorkspaceChangesHashResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.RefreshGithubAccessToken
     */
    refreshGithubAccessToken: {
      name: "RefreshGithubAccessToken",
      I: RefreshGithubAccessTokenRequest,
      O: RefreshGithubAccessTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.WarmRemoteAccessServer
     */
    warmRemoteAccessServer: {
      name: "WarmRemoteAccessServer",
      I: WarmRemoteAccessServerRequest,
      O: WarmRemoteAccessServerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.ListArtifacts
     */
    listArtifacts: {
      name: "ListArtifacts",
      I: ListArtifactsRequest,
      O: ListArtifactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.UploadArtifacts
     */
    uploadArtifacts: {
      name: "UploadArtifacts",
      I: UploadArtifactsRequest,
      O: UploadArtifactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.GetMcpRefreshTokens
     */
    getMcpRefreshTokens: {
      name: "GetMcpRefreshTokens",
      I: GetMcpRefreshTokensRequest,
      O: GetMcpRefreshTokensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.ControlService.UpdateEnvironmentVariables
     */
    updateEnvironmentVariables: {
      name: "UpdateEnvironmentVariables",
      I: UpdateEnvironmentVariablesRequest,
      O: UpdateEnvironmentVariablesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service agent.v1.LifecycleService
 */
export const LifecycleService = {
  typeName: "agent.v1.LifecycleService",
  methods: {
    /**
     * @generated from rpc agent.v1.LifecycleService.ResetInstance
     */
    resetInstance: {
      name: "ResetInstance",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc agent.v1.LifecycleService.RenewInstance
     */
    renewInstance: {
      name: "RenewInstance",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

