// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/control_service.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { ArtifactUploadDispatchStatus, ArtifactUploadStatus } from "./agent_pb.js";

/**
 * @generated from message agent.v1.PingResponse
 */
export class PingResponse extends Message<PingResponse> {
  constructor(data?: PartialMessage<PingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.PingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PingResponse {
    return new PingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PingResponse {
    return new PingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PingResponse {
    return new PingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PingResponse | PlainMessage<PingResponse> | undefined, b: PingResponse | PlainMessage<PingResponse> | undefined): boolean {
    return proto3.util.equals(PingResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.ExecRequest
 */
export class ExecRequest extends Message<ExecRequest> {
  /**
   * @generated from field: string command = 1;
   */
  command = "";

  /**
   * @generated from field: optional string cwd = 2;
   */
  cwd?: string;

  /**
   * @generated from field: repeated string args = 3;
   */
  args: string[] = [];

  /**
   * @generated from field: map<string, string> environment = 4;
   */
  environment: { [key: string]: string } = {};

  constructor(data?: PartialMessage<ExecRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExecRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "cwd", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "args", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "environment", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExecRequest {
    return new ExecRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExecRequest {
    return new ExecRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExecRequest {
    return new ExecRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExecRequest | PlainMessage<ExecRequest> | undefined, b: ExecRequest | PlainMessage<ExecRequest> | undefined): boolean {
    return proto3.util.equals(ExecRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.ExecResponse
 */
export class ExecResponse extends Message<ExecResponse> {
  /**
   * @generated from oneof agent.v1.ExecResponse.event
   */
  event: {
    /**
     * @generated from field: agent.v1.StdoutEvent stdout_event = 1;
     */
    value: StdoutEvent;
    case: "stdoutEvent";
  } | {
    /**
     * @generated from field: agent.v1.StderrEvent stderr_event = 2;
     */
    value: StderrEvent;
    case: "stderrEvent";
  } | {
    /**
     * @generated from field: agent.v1.ExitEvent exit_event = 3;
     */
    value: ExitEvent;
    case: "exitEvent";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ExecResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExecResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stdout_event", kind: "message", T: StdoutEvent, oneof: "event" },
    { no: 2, name: "stderr_event", kind: "message", T: StderrEvent, oneof: "event" },
    { no: 3, name: "exit_event", kind: "message", T: ExitEvent, oneof: "event" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExecResponse {
    return new ExecResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExecResponse {
    return new ExecResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExecResponse {
    return new ExecResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExecResponse | PlainMessage<ExecResponse> | undefined, b: ExecResponse | PlainMessage<ExecResponse> | undefined): boolean {
    return proto3.util.equals(ExecResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.StdoutEvent
 */
export class StdoutEvent extends Message<StdoutEvent> {
  /**
   * @generated from field: string data = 1;
   */
  data = "";

  constructor(data?: PartialMessage<StdoutEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StdoutEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StdoutEvent {
    return new StdoutEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StdoutEvent {
    return new StdoutEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StdoutEvent {
    return new StdoutEvent().fromJsonString(jsonString, options);
  }

  static equals(a: StdoutEvent | PlainMessage<StdoutEvent> | undefined, b: StdoutEvent | PlainMessage<StdoutEvent> | undefined): boolean {
    return proto3.util.equals(StdoutEvent, a, b);
  }
}

/**
 * @generated from message agent.v1.StderrEvent
 */
export class StderrEvent extends Message<StderrEvent> {
  /**
   * @generated from field: string data = 1;
   */
  data = "";

  constructor(data?: PartialMessage<StderrEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StderrEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StderrEvent {
    return new StderrEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StderrEvent {
    return new StderrEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StderrEvent {
    return new StderrEvent().fromJsonString(jsonString, options);
  }

  static equals(a: StderrEvent | PlainMessage<StderrEvent> | undefined, b: StderrEvent | PlainMessage<StderrEvent> | undefined): boolean {
    return proto3.util.equals(StderrEvent, a, b);
  }
}

/**
 * @generated from message agent.v1.ExitEvent
 */
export class ExitEvent extends Message<ExitEvent> {
  /**
   * @generated from field: int32 exit_code = 1;
   */
  exitCode = 0;

  constructor(data?: PartialMessage<ExitEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExitEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "exit_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExitEvent {
    return new ExitEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExitEvent {
    return new ExitEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExitEvent {
    return new ExitEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ExitEvent | PlainMessage<ExitEvent> | undefined, b: ExitEvent | PlainMessage<ExitEvent> | undefined): boolean {
    return proto3.util.equals(ExitEvent, a, b);
  }
}

/**
 * @generated from message agent.v1.ReadTextFileRequest
 */
export class ReadTextFileRequest extends Message<ReadTextFileRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<ReadTextFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReadTextFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadTextFileRequest {
    return new ReadTextFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadTextFileRequest {
    return new ReadTextFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadTextFileRequest {
    return new ReadTextFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReadTextFileRequest | PlainMessage<ReadTextFileRequest> | undefined, b: ReadTextFileRequest | PlainMessage<ReadTextFileRequest> | undefined): boolean {
    return proto3.util.equals(ReadTextFileRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.ReadTextFileResponse
 */
export class ReadTextFileResponse extends Message<ReadTextFileResponse> {
  /**
   * @generated from field: string content = 1;
   */
  content = "";

  constructor(data?: PartialMessage<ReadTextFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReadTextFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadTextFileResponse {
    return new ReadTextFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadTextFileResponse {
    return new ReadTextFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadTextFileResponse {
    return new ReadTextFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReadTextFileResponse | PlainMessage<ReadTextFileResponse> | undefined, b: ReadTextFileResponse | PlainMessage<ReadTextFileResponse> | undefined): boolean {
    return proto3.util.equals(ReadTextFileResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.WriteTextFileRequest
 */
export class WriteTextFileRequest extends Message<WriteTextFileRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  constructor(data?: PartialMessage<WriteTextFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WriteTextFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteTextFileRequest {
    return new WriteTextFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteTextFileRequest {
    return new WriteTextFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteTextFileRequest {
    return new WriteTextFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WriteTextFileRequest | PlainMessage<WriteTextFileRequest> | undefined, b: WriteTextFileRequest | PlainMessage<WriteTextFileRequest> | undefined): boolean {
    return proto3.util.equals(WriteTextFileRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.WriteTextFileResponse
 */
export class WriteTextFileResponse extends Message<WriteTextFileResponse> {
  constructor(data?: PartialMessage<WriteTextFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WriteTextFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteTextFileResponse {
    return new WriteTextFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteTextFileResponse {
    return new WriteTextFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteTextFileResponse {
    return new WriteTextFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WriteTextFileResponse | PlainMessage<WriteTextFileResponse> | undefined, b: WriteTextFileResponse | PlainMessage<WriteTextFileResponse> | undefined): boolean {
    return proto3.util.equals(WriteTextFileResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.ReadBinaryFileRequest
 */
export class ReadBinaryFileRequest extends Message<ReadBinaryFileRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<ReadBinaryFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReadBinaryFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadBinaryFileRequest {
    return new ReadBinaryFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadBinaryFileRequest {
    return new ReadBinaryFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadBinaryFileRequest {
    return new ReadBinaryFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReadBinaryFileRequest | PlainMessage<ReadBinaryFileRequest> | undefined, b: ReadBinaryFileRequest | PlainMessage<ReadBinaryFileRequest> | undefined): boolean {
    return proto3.util.equals(ReadBinaryFileRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.ReadBinaryFileResponse
 */
export class ReadBinaryFileResponse extends Message<ReadBinaryFileResponse> {
  /**
   * @generated from field: bytes content = 1;
   */
  content = new Uint8Array(0);

  constructor(data?: PartialMessage<ReadBinaryFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReadBinaryFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadBinaryFileResponse {
    return new ReadBinaryFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadBinaryFileResponse {
    return new ReadBinaryFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadBinaryFileResponse {
    return new ReadBinaryFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReadBinaryFileResponse | PlainMessage<ReadBinaryFileResponse> | undefined, b: ReadBinaryFileResponse | PlainMessage<ReadBinaryFileResponse> | undefined): boolean {
    return proto3.util.equals(ReadBinaryFileResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.WriteBinaryFileRequest
 */
export class WriteBinaryFileRequest extends Message<WriteBinaryFileRequest> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: bytes content = 2;
   */
  content = new Uint8Array(0);

  constructor(data?: PartialMessage<WriteBinaryFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WriteBinaryFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteBinaryFileRequest {
    return new WriteBinaryFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteBinaryFileRequest {
    return new WriteBinaryFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteBinaryFileRequest {
    return new WriteBinaryFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WriteBinaryFileRequest | PlainMessage<WriteBinaryFileRequest> | undefined, b: WriteBinaryFileRequest | PlainMessage<WriteBinaryFileRequest> | undefined): boolean {
    return proto3.util.equals(WriteBinaryFileRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.WriteBinaryFileResponse
 */
export class WriteBinaryFileResponse extends Message<WriteBinaryFileResponse> {
  constructor(data?: PartialMessage<WriteBinaryFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WriteBinaryFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteBinaryFileResponse {
    return new WriteBinaryFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteBinaryFileResponse {
    return new WriteBinaryFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteBinaryFileResponse {
    return new WriteBinaryFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WriteBinaryFileResponse | PlainMessage<WriteBinaryFileResponse> | undefined, b: WriteBinaryFileResponse | PlainMessage<WriteBinaryFileResponse> | undefined): boolean {
    return proto3.util.equals(WriteBinaryFileResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.GetWorkspaceChangesHashRequest
 */
export class GetWorkspaceChangesHashRequest extends Message<GetWorkspaceChangesHashRequest> {
  /**
   * @generated from field: string root_path = 1;
   */
  rootPath = "";

  /**
   * @generated from field: string base_ref = 2;
   */
  baseRef = "";

  constructor(data?: PartialMessage<GetWorkspaceChangesHashRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GetWorkspaceChangesHashRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "root_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "base_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkspaceChangesHashRequest {
    return new GetWorkspaceChangesHashRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkspaceChangesHashRequest {
    return new GetWorkspaceChangesHashRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkspaceChangesHashRequest {
    return new GetWorkspaceChangesHashRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkspaceChangesHashRequest | PlainMessage<GetWorkspaceChangesHashRequest> | undefined, b: GetWorkspaceChangesHashRequest | PlainMessage<GetWorkspaceChangesHashRequest> | undefined): boolean {
    return proto3.util.equals(GetWorkspaceChangesHashRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.GetWorkspaceChangesHashResponse
 */
export class GetWorkspaceChangesHashResponse extends Message<GetWorkspaceChangesHashResponse> {
  /**
   * @generated from field: string hash = 1;
   */
  hash = "";

  constructor(data?: PartialMessage<GetWorkspaceChangesHashResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GetWorkspaceChangesHashResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetWorkspaceChangesHashResponse {
    return new GetWorkspaceChangesHashResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetWorkspaceChangesHashResponse {
    return new GetWorkspaceChangesHashResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetWorkspaceChangesHashResponse {
    return new GetWorkspaceChangesHashResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetWorkspaceChangesHashResponse | PlainMessage<GetWorkspaceChangesHashResponse> | undefined, b: GetWorkspaceChangesHashResponse | PlainMessage<GetWorkspaceChangesHashResponse> | undefined): boolean {
    return proto3.util.equals(GetWorkspaceChangesHashResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.RefreshGithubAccessTokenRequest
 */
export class RefreshGithubAccessTokenRequest extends Message<RefreshGithubAccessTokenRequest> {
  /**
   * @generated from field: string github_access_token = 1;
   */
  githubAccessToken = "";

  /**
   * @generated from field: string hostname = 2;
   */
  hostname = "";

  constructor(data?: PartialMessage<RefreshGithubAccessTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RefreshGithubAccessTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "github_access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "hostname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshGithubAccessTokenRequest {
    return new RefreshGithubAccessTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshGithubAccessTokenRequest {
    return new RefreshGithubAccessTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshGithubAccessTokenRequest {
    return new RefreshGithubAccessTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshGithubAccessTokenRequest | PlainMessage<RefreshGithubAccessTokenRequest> | undefined, b: RefreshGithubAccessTokenRequest | PlainMessage<RefreshGithubAccessTokenRequest> | undefined): boolean {
    return proto3.util.equals(RefreshGithubAccessTokenRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.RefreshGithubAccessTokenResponse
 */
export class RefreshGithubAccessTokenResponse extends Message<RefreshGithubAccessTokenResponse> {
  constructor(data?: PartialMessage<RefreshGithubAccessTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RefreshGithubAccessTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshGithubAccessTokenResponse {
    return new RefreshGithubAccessTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshGithubAccessTokenResponse {
    return new RefreshGithubAccessTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshGithubAccessTokenResponse {
    return new RefreshGithubAccessTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshGithubAccessTokenResponse | PlainMessage<RefreshGithubAccessTokenResponse> | undefined, b: RefreshGithubAccessTokenResponse | PlainMessage<RefreshGithubAccessTokenResponse> | undefined): boolean {
    return proto3.util.equals(RefreshGithubAccessTokenResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.WarmRemoteAccessServerRequest
 */
export class WarmRemoteAccessServerRequest extends Message<WarmRemoteAccessServerRequest> {
  /**
   * @generated from field: string commit = 1;
   */
  commit = "";

  /**
   * @generated from field: int32 port = 2;
   */
  port = 0;

  /**
   * @generated from field: string connection_token = 3;
   */
  connectionToken = "";

  constructor(data?: PartialMessage<WarmRemoteAccessServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WarmRemoteAccessServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "commit", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "connection_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WarmRemoteAccessServerRequest {
    return new WarmRemoteAccessServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WarmRemoteAccessServerRequest {
    return new WarmRemoteAccessServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WarmRemoteAccessServerRequest {
    return new WarmRemoteAccessServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WarmRemoteAccessServerRequest | PlainMessage<WarmRemoteAccessServerRequest> | undefined, b: WarmRemoteAccessServerRequest | PlainMessage<WarmRemoteAccessServerRequest> | undefined): boolean {
    return proto3.util.equals(WarmRemoteAccessServerRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.WarmRemoteAccessServerResponse
 */
export class WarmRemoteAccessServerResponse extends Message<WarmRemoteAccessServerResponse> {
  constructor(data?: PartialMessage<WarmRemoteAccessServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WarmRemoteAccessServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WarmRemoteAccessServerResponse {
    return new WarmRemoteAccessServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WarmRemoteAccessServerResponse {
    return new WarmRemoteAccessServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WarmRemoteAccessServerResponse {
    return new WarmRemoteAccessServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WarmRemoteAccessServerResponse | PlainMessage<WarmRemoteAccessServerResponse> | undefined, b: WarmRemoteAccessServerResponse | PlainMessage<WarmRemoteAccessServerResponse> | undefined): boolean {
    return proto3.util.equals(WarmRemoteAccessServerResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.ListArtifactsRequest
 */
export class ListArtifactsRequest extends Message<ListArtifactsRequest> {
  constructor(data?: PartialMessage<ListArtifactsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ListArtifactsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtifactsRequest {
    return new ListArtifactsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtifactsRequest {
    return new ListArtifactsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtifactsRequest {
    return new ListArtifactsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListArtifactsRequest | PlainMessage<ListArtifactsRequest> | undefined, b: ListArtifactsRequest | PlainMessage<ListArtifactsRequest> | undefined): boolean {
    return proto3.util.equals(ListArtifactsRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.ArtifactUploadMetadata
 */
export class ArtifactUploadMetadata extends Message<ArtifactUploadMetadata> {
  /**
   * @generated from field: string absolute_path = 1;
   */
  absolutePath = "";

  /**
   * @generated from field: uint64 size_bytes = 2;
   */
  sizeBytes = protoInt64.zero;

  /**
   * @generated from field: int64 updated_at_unix_ms = 3;
   */
  updatedAtUnixMs = protoInt64.zero;

  /**
   * @generated from field: agent.v1.ArtifactUploadStatus status = 4;
   */
  status = ArtifactUploadStatus.UNSPECIFIED;

  /**
   * @generated from field: uint64 bytes_uploaded = 5;
   */
  bytesUploaded = protoInt64.zero;

  /**
   * @generated from field: string last_error = 6;
   */
  lastError = "";

  /**
   * @generated from field: uint32 upload_attempts = 7;
   */
  uploadAttempts = 0;

  /**
   * @generated from field: int64 last_started_at_unix_ms = 8;
   */
  lastStartedAtUnixMs = protoInt64.zero;

  /**
   * @generated from field: int64 last_finished_at_unix_ms = 9;
   */
  lastFinishedAtUnixMs = protoInt64.zero;

  /**
   * @generated from field: string upload_id = 10;
   */
  uploadId = "";

  constructor(data?: PartialMessage<ArtifactUploadMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ArtifactUploadMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "size_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "updated_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(ArtifactUploadStatus) },
    { no: 5, name: "bytes_uploaded", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "last_error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "upload_attempts", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "last_started_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "last_finished_at_unix_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "upload_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ArtifactUploadMetadata {
    return new ArtifactUploadMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ArtifactUploadMetadata {
    return new ArtifactUploadMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ArtifactUploadMetadata {
    return new ArtifactUploadMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: ArtifactUploadMetadata | PlainMessage<ArtifactUploadMetadata> | undefined, b: ArtifactUploadMetadata | PlainMessage<ArtifactUploadMetadata> | undefined): boolean {
    return proto3.util.equals(ArtifactUploadMetadata, a, b);
  }
}

/**
 * @generated from message agent.v1.ListArtifactsResponse
 */
export class ListArtifactsResponse extends Message<ListArtifactsResponse> {
  /**
   * @generated from field: repeated agent.v1.ArtifactUploadMetadata artifacts = 1;
   */
  artifacts: ArtifactUploadMetadata[] = [];

  constructor(data?: PartialMessage<ListArtifactsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ListArtifactsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "artifacts", kind: "message", T: ArtifactUploadMetadata, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtifactsResponse {
    return new ListArtifactsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtifactsResponse {
    return new ListArtifactsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtifactsResponse {
    return new ListArtifactsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListArtifactsResponse | PlainMessage<ListArtifactsResponse> | undefined, b: ListArtifactsResponse | PlainMessage<ListArtifactsResponse> | undefined): boolean {
    return proto3.util.equals(ListArtifactsResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.UploadArtifactsRequest
 */
export class UploadArtifactsRequest extends Message<UploadArtifactsRequest> {
  /**
   * @generated from field: repeated agent.v1.ArtifactUploadInstruction uploads = 1;
   */
  uploads: ArtifactUploadInstruction[] = [];

  constructor(data?: PartialMessage<UploadArtifactsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.UploadArtifactsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uploads", kind: "message", T: ArtifactUploadInstruction, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadArtifactsRequest {
    return new UploadArtifactsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadArtifactsRequest {
    return new UploadArtifactsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadArtifactsRequest {
    return new UploadArtifactsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadArtifactsRequest | PlainMessage<UploadArtifactsRequest> | undefined, b: UploadArtifactsRequest | PlainMessage<UploadArtifactsRequest> | undefined): boolean {
    return proto3.util.equals(UploadArtifactsRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.ArtifactUploadInstruction
 */
export class ArtifactUploadInstruction extends Message<ArtifactUploadInstruction> {
  /**
   * @generated from field: string absolute_path = 1;
   */
  absolutePath = "";

  /**
   * @generated from field: string upload_url = 2;
   */
  uploadUrl = "";

  /**
   * @generated from field: string method = 3;
   */
  method = "";

  /**
   * @generated from field: map<string, string> headers = 4;
   */
  headers: { [key: string]: string } = {};

  /**
   * @generated from field: optional string content_type = 5;
   */
  contentType?: string;

  /**
   * @generated from field: optional string slack_upload_url = 6;
   */
  slackUploadUrl?: string;

  /**
   * @generated from field: optional string slack_file_id = 7;
   */
  slackFileId?: string;

  constructor(data?: PartialMessage<ArtifactUploadInstruction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ArtifactUploadInstruction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "upload_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "headers", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 5, name: "content_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "slack_upload_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "slack_file_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ArtifactUploadInstruction {
    return new ArtifactUploadInstruction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ArtifactUploadInstruction {
    return new ArtifactUploadInstruction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ArtifactUploadInstruction {
    return new ArtifactUploadInstruction().fromJsonString(jsonString, options);
  }

  static equals(a: ArtifactUploadInstruction | PlainMessage<ArtifactUploadInstruction> | undefined, b: ArtifactUploadInstruction | PlainMessage<ArtifactUploadInstruction> | undefined): boolean {
    return proto3.util.equals(ArtifactUploadInstruction, a, b);
  }
}

/**
 * @generated from message agent.v1.ArtifactUploadDispatchResult
 */
export class ArtifactUploadDispatchResult extends Message<ArtifactUploadDispatchResult> {
  /**
   * @generated from field: string absolute_path = 1;
   */
  absolutePath = "";

  /**
   * @generated from field: agent.v1.ArtifactUploadDispatchStatus status = 2;
   */
  status = ArtifactUploadDispatchStatus.UNSPECIFIED;

  /**
   * @generated from field: string message = 3;
   */
  message = "";

  /**
   * @generated from field: optional string slack_file_id = 4;
   */
  slackFileId?: string;

  constructor(data?: PartialMessage<ArtifactUploadDispatchResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ArtifactUploadDispatchResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(ArtifactUploadDispatchStatus) },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "slack_file_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ArtifactUploadDispatchResult {
    return new ArtifactUploadDispatchResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ArtifactUploadDispatchResult {
    return new ArtifactUploadDispatchResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ArtifactUploadDispatchResult {
    return new ArtifactUploadDispatchResult().fromJsonString(jsonString, options);
  }

  static equals(a: ArtifactUploadDispatchResult | PlainMessage<ArtifactUploadDispatchResult> | undefined, b: ArtifactUploadDispatchResult | PlainMessage<ArtifactUploadDispatchResult> | undefined): boolean {
    return proto3.util.equals(ArtifactUploadDispatchResult, a, b);
  }
}

/**
 * @generated from message agent.v1.UploadArtifactsResponse
 */
export class UploadArtifactsResponse extends Message<UploadArtifactsResponse> {
  /**
   * @generated from field: repeated agent.v1.ArtifactUploadDispatchResult results = 1;
   */
  results: ArtifactUploadDispatchResult[] = [];

  constructor(data?: PartialMessage<UploadArtifactsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.UploadArtifactsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "results", kind: "message", T: ArtifactUploadDispatchResult, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadArtifactsResponse {
    return new UploadArtifactsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadArtifactsResponse {
    return new UploadArtifactsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadArtifactsResponse {
    return new UploadArtifactsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadArtifactsResponse | PlainMessage<UploadArtifactsResponse> | undefined, b: UploadArtifactsResponse | PlainMessage<UploadArtifactsResponse> | undefined): boolean {
    return proto3.util.equals(UploadArtifactsResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.GetMcpRefreshTokensRequest
 */
export class GetMcpRefreshTokensRequest extends Message<GetMcpRefreshTokensRequest> {
  constructor(data?: PartialMessage<GetMcpRefreshTokensRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GetMcpRefreshTokensRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMcpRefreshTokensRequest {
    return new GetMcpRefreshTokensRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMcpRefreshTokensRequest {
    return new GetMcpRefreshTokensRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMcpRefreshTokensRequest {
    return new GetMcpRefreshTokensRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMcpRefreshTokensRequest | PlainMessage<GetMcpRefreshTokensRequest> | undefined, b: GetMcpRefreshTokensRequest | PlainMessage<GetMcpRefreshTokensRequest> | undefined): boolean {
    return proto3.util.equals(GetMcpRefreshTokensRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.GetMcpRefreshTokensResponse
 */
export class GetMcpRefreshTokensResponse extends Message<GetMcpRefreshTokensResponse> {
  /**
   * @generated from field: map<string, string> refresh_tokens = 1;
   */
  refreshTokens: { [key: string]: string } = {};

  constructor(data?: PartialMessage<GetMcpRefreshTokensResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GetMcpRefreshTokensResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refresh_tokens", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMcpRefreshTokensResponse {
    return new GetMcpRefreshTokensResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMcpRefreshTokensResponse {
    return new GetMcpRefreshTokensResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMcpRefreshTokensResponse {
    return new GetMcpRefreshTokensResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMcpRefreshTokensResponse | PlainMessage<GetMcpRefreshTokensResponse> | undefined, b: GetMcpRefreshTokensResponse | PlainMessage<GetMcpRefreshTokensResponse> | undefined): boolean {
    return proto3.util.equals(GetMcpRefreshTokensResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.UpdateEnvironmentVariablesRequest
 */
export class UpdateEnvironmentVariablesRequest extends Message<UpdateEnvironmentVariablesRequest> {
  /**
   * @generated from field: map<string, string> env = 1;
   */
  env: { [key: string]: string } = {};

  /**
   * @generated from field: bool replace = 2;
   */
  replace = false;

  constructor(data?: PartialMessage<UpdateEnvironmentVariablesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.UpdateEnvironmentVariablesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "env", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 2, name: "replace", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEnvironmentVariablesRequest {
    return new UpdateEnvironmentVariablesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEnvironmentVariablesRequest {
    return new UpdateEnvironmentVariablesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEnvironmentVariablesRequest {
    return new UpdateEnvironmentVariablesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEnvironmentVariablesRequest | PlainMessage<UpdateEnvironmentVariablesRequest> | undefined, b: UpdateEnvironmentVariablesRequest | PlainMessage<UpdateEnvironmentVariablesRequest> | undefined): boolean {
    return proto3.util.equals(UpdateEnvironmentVariablesRequest, a, b);
  }
}

/**
 * @generated from message agent.v1.UpdateEnvironmentVariablesResponse
 */
export class UpdateEnvironmentVariablesResponse extends Message<UpdateEnvironmentVariablesResponse> {
  /**
   * @generated from field: uint32 applied = 1;
   */
  applied = 0;

  /**
   * @generated from field: uint32 removed = 2;
   */
  removed = 0;

  constructor(data?: PartialMessage<UpdateEnvironmentVariablesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.UpdateEnvironmentVariablesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "applied", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "removed", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEnvironmentVariablesResponse {
    return new UpdateEnvironmentVariablesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEnvironmentVariablesResponse {
    return new UpdateEnvironmentVariablesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEnvironmentVariablesResponse {
    return new UpdateEnvironmentVariablesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEnvironmentVariablesResponse | PlainMessage<UpdateEnvironmentVariablesResponse> | undefined, b: UpdateEnvironmentVariablesResponse | PlainMessage<UpdateEnvironmentVariablesResponse> | undefined): boolean {
    return proto3.util.equals(UpdateEnvironmentVariablesResponse, a, b);
  }
}

