// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/create_plan_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { TodoItem } from "./todo_tool_pb.js";

/**
 * @generated from message agent.v1.CreatePlanToolCall
 */
export class CreatePlanToolCall extends Message<CreatePlanToolCall> {
  /**
   * @generated from field: agent.v1.CreatePlanArgs args = 1;
   */
  args?: CreatePlanArgs;

  /**
   * @generated from field: agent.v1.CreatePlanResult result = 2;
   */
  result?: CreatePlanResult;

  constructor(data?: PartialMessage<CreatePlanToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: CreatePlanArgs },
    { no: 2, name: "result", kind: "message", T: CreatePlanResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanToolCall {
    return new CreatePlanToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanToolCall {
    return new CreatePlanToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanToolCall {
    return new CreatePlanToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanToolCall | PlainMessage<CreatePlanToolCall> | undefined, b: CreatePlanToolCall | PlainMessage<CreatePlanToolCall> | undefined): boolean {
    return proto3.util.equals(CreatePlanToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.Phase
 */
export class Phase extends Message<Phase> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: repeated agent.v1.TodoItem todos = 2;
   */
  todos: TodoItem[] = [];

  constructor(data?: PartialMessage<Phase>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.Phase";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "todos", kind: "message", T: TodoItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Phase {
    return new Phase().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Phase {
    return new Phase().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Phase {
    return new Phase().fromJsonString(jsonString, options);
  }

  static equals(a: Phase | PlainMessage<Phase> | undefined, b: Phase | PlainMessage<Phase> | undefined): boolean {
    return proto3.util.equals(Phase, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanArgs
 */
export class CreatePlanArgs extends Message<CreatePlanArgs> {
  /**
   * @generated from field: string plan = 1;
   */
  plan = "";

  /**
   * @generated from field: repeated agent.v1.TodoItem todos = 2;
   */
  todos: TodoItem[] = [];

  /**
   * @generated from field: string overview = 3;
   */
  overview = "";

  /**
   * @generated from field: string name = 4;
   */
  name = "";

  /**
   * @generated from field: bool is_project = 5;
   */
  isProject = false;

  /**
   * @generated from field: repeated agent.v1.Phase phases = 6;
   */
  phases: Phase[] = [];

  constructor(data?: PartialMessage<CreatePlanArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "plan", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "todos", kind: "message", T: TodoItem, repeated: true },
    { no: 3, name: "overview", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "is_project", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "phases", kind: "message", T: Phase, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanArgs {
    return new CreatePlanArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanArgs {
    return new CreatePlanArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanArgs {
    return new CreatePlanArgs().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanArgs | PlainMessage<CreatePlanArgs> | undefined, b: CreatePlanArgs | PlainMessage<CreatePlanArgs> | undefined): boolean {
    return proto3.util.equals(CreatePlanArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanResult
 */
export class CreatePlanResult extends Message<CreatePlanResult> {
  /**
   * @generated from field: string plan_uri = 3;
   */
  planUri = "";

  /**
   * @generated from oneof agent.v1.CreatePlanResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.CreatePlanSuccess success = 1;
     */
    value: CreatePlanSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.CreatePlanError error = 2;
     */
    value: CreatePlanError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<CreatePlanResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "plan_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 1, name: "success", kind: "message", T: CreatePlanSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: CreatePlanError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanResult {
    return new CreatePlanResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanResult {
    return new CreatePlanResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanResult {
    return new CreatePlanResult().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanResult | PlainMessage<CreatePlanResult> | undefined, b: CreatePlanResult | PlainMessage<CreatePlanResult> | undefined): boolean {
    return proto3.util.equals(CreatePlanResult, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanSuccess
 */
export class CreatePlanSuccess extends Message<CreatePlanSuccess> {
  constructor(data?: PartialMessage<CreatePlanSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanSuccess {
    return new CreatePlanSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanSuccess {
    return new CreatePlanSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanSuccess {
    return new CreatePlanSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanSuccess | PlainMessage<CreatePlanSuccess> | undefined, b: CreatePlanSuccess | PlainMessage<CreatePlanSuccess> | undefined): boolean {
    return proto3.util.equals(CreatePlanSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanError
 */
export class CreatePlanError extends Message<CreatePlanError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<CreatePlanError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanError {
    return new CreatePlanError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanError {
    return new CreatePlanError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanError {
    return new CreatePlanError().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanError | PlainMessage<CreatePlanError> | undefined, b: CreatePlanError | PlainMessage<CreatePlanError> | undefined): boolean {
    return proto3.util.equals(CreatePlanError, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanRequestQuery
 */
export class CreatePlanRequestQuery extends Message<CreatePlanRequestQuery> {
  /**
   * @generated from field: agent.v1.CreatePlanArgs args = 1;
   */
  args?: CreatePlanArgs;

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<CreatePlanRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: CreatePlanArgs },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanRequestQuery {
    return new CreatePlanRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanRequestQuery {
    return new CreatePlanRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanRequestQuery {
    return new CreatePlanRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanRequestQuery | PlainMessage<CreatePlanRequestQuery> | undefined, b: CreatePlanRequestQuery | PlainMessage<CreatePlanRequestQuery> | undefined): boolean {
    return proto3.util.equals(CreatePlanRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.CreatePlanRequestResponse
 */
export class CreatePlanRequestResponse extends Message<CreatePlanRequestResponse> {
  /**
   * @generated from field: agent.v1.CreatePlanResult result = 1;
   */
  result?: CreatePlanResult;

  constructor(data?: PartialMessage<CreatePlanRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CreatePlanRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "message", T: CreatePlanResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlanRequestResponse {
    return new CreatePlanRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlanRequestResponse {
    return new CreatePlanRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlanRequestResponse {
    return new CreatePlanRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlanRequestResponse | PlainMessage<CreatePlanRequestResponse> | undefined, b: CreatePlanRequestResponse | PlainMessage<CreatePlanRequestResponse> | undefined): boolean {
    return proto3.util.equals(CreatePlanRequestResponse, a, b);
  }
}

