// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/cursor_rules.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum agent.v1.CursorRuleSource
 */
export enum CursorRuleSource {
  /**
   * @generated from enum value: CURSOR_RULE_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CURSOR_RULE_SOURCE_TEAM = 1;
   */
  TEAM = 1,

  /**
   * @generated from enum value: CURSOR_RULE_SOURCE_USER = 2;
   */
  USER = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(CursorRuleSource)
proto3.util.setEnumType(CursorRuleSource, "agent.v1.CursorRuleSource", [
  { no: 0, name: "CURSOR_RULE_SOURCE_UNSPECIFIED" },
  { no: 1, name: "CURSOR_RULE_SOURCE_TEAM" },
  { no: 2, name: "CURSOR_RULE_SOURCE_USER" },
]);

/**
 * @generated from message agent.v1.CursorRuleTypeGlobal
 */
export class CursorRuleTypeGlobal extends Message<CursorRuleTypeGlobal> {
  constructor(data?: PartialMessage<CursorRuleTypeGlobal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRuleTypeGlobal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRuleTypeGlobal {
    return new CursorRuleTypeGlobal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRuleTypeGlobal {
    return new CursorRuleTypeGlobal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRuleTypeGlobal {
    return new CursorRuleTypeGlobal().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRuleTypeGlobal | PlainMessage<CursorRuleTypeGlobal> | undefined, b: CursorRuleTypeGlobal | PlainMessage<CursorRuleTypeGlobal> | undefined): boolean {
    return proto3.util.equals(CursorRuleTypeGlobal, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorRuleTypeFileGlobs
 */
export class CursorRuleTypeFileGlobs extends Message<CursorRuleTypeFileGlobs> {
  /**
   * @generated from field: repeated string globs = 1;
   */
  globs: string[] = [];

  constructor(data?: PartialMessage<CursorRuleTypeFileGlobs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRuleTypeFileGlobs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "globs", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRuleTypeFileGlobs {
    return new CursorRuleTypeFileGlobs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRuleTypeFileGlobs {
    return new CursorRuleTypeFileGlobs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRuleTypeFileGlobs {
    return new CursorRuleTypeFileGlobs().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRuleTypeFileGlobs | PlainMessage<CursorRuleTypeFileGlobs> | undefined, b: CursorRuleTypeFileGlobs | PlainMessage<CursorRuleTypeFileGlobs> | undefined): boolean {
    return proto3.util.equals(CursorRuleTypeFileGlobs, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorRuleTypeAgentFetched
 */
export class CursorRuleTypeAgentFetched extends Message<CursorRuleTypeAgentFetched> {
  /**
   * @generated from field: string description = 1;
   */
  description = "";

  constructor(data?: PartialMessage<CursorRuleTypeAgentFetched>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRuleTypeAgentFetched";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRuleTypeAgentFetched {
    return new CursorRuleTypeAgentFetched().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRuleTypeAgentFetched {
    return new CursorRuleTypeAgentFetched().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRuleTypeAgentFetched {
    return new CursorRuleTypeAgentFetched().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRuleTypeAgentFetched | PlainMessage<CursorRuleTypeAgentFetched> | undefined, b: CursorRuleTypeAgentFetched | PlainMessage<CursorRuleTypeAgentFetched> | undefined): boolean {
    return proto3.util.equals(CursorRuleTypeAgentFetched, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorRuleTypeManuallyAttached
 */
export class CursorRuleTypeManuallyAttached extends Message<CursorRuleTypeManuallyAttached> {
  constructor(data?: PartialMessage<CursorRuleTypeManuallyAttached>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRuleTypeManuallyAttached";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRuleTypeManuallyAttached {
    return new CursorRuleTypeManuallyAttached().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRuleTypeManuallyAttached {
    return new CursorRuleTypeManuallyAttached().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRuleTypeManuallyAttached {
    return new CursorRuleTypeManuallyAttached().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRuleTypeManuallyAttached | PlainMessage<CursorRuleTypeManuallyAttached> | undefined, b: CursorRuleTypeManuallyAttached | PlainMessage<CursorRuleTypeManuallyAttached> | undefined): boolean {
    return proto3.util.equals(CursorRuleTypeManuallyAttached, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorRuleType
 */
export class CursorRuleType extends Message<CursorRuleType> {
  /**
   * @generated from oneof agent.v1.CursorRuleType.type
   */
  type: {
    /**
     * @generated from field: agent.v1.CursorRuleTypeGlobal global = 1;
     */
    value: CursorRuleTypeGlobal;
    case: "global";
  } | {
    /**
     * @generated from field: agent.v1.CursorRuleTypeFileGlobs file_globbed = 2;
     */
    value: CursorRuleTypeFileGlobs;
    case: "fileGlobbed";
  } | {
    /**
     * @generated from field: agent.v1.CursorRuleTypeAgentFetched agent_fetched = 3;
     */
    value: CursorRuleTypeAgentFetched;
    case: "agentFetched";
  } | {
    /**
     * @generated from field: agent.v1.CursorRuleTypeManuallyAttached manually_attached = 4;
     */
    value: CursorRuleTypeManuallyAttached;
    case: "manuallyAttached";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<CursorRuleType>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRuleType";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "global", kind: "message", T: CursorRuleTypeGlobal, oneof: "type" },
    { no: 2, name: "file_globbed", kind: "message", T: CursorRuleTypeFileGlobs, oneof: "type" },
    { no: 3, name: "agent_fetched", kind: "message", T: CursorRuleTypeAgentFetched, oneof: "type" },
    { no: 4, name: "manually_attached", kind: "message", T: CursorRuleTypeManuallyAttached, oneof: "type" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRuleType {
    return new CursorRuleType().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRuleType {
    return new CursorRuleType().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRuleType {
    return new CursorRuleType().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRuleType | PlainMessage<CursorRuleType> | undefined, b: CursorRuleType | PlainMessage<CursorRuleType> | undefined): boolean {
    return proto3.util.equals(CursorRuleType, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorRule
 */
export class CursorRule extends Message<CursorRule> {
  /**
   * @generated from field: string full_path = 1;
   */
  fullPath = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: agent.v1.CursorRuleType type = 3;
   */
  type?: CursorRuleType;

  /**
   * @generated from field: agent.v1.CursorRuleSource source = 4;
   */
  source = CursorRuleSource.UNSPECIFIED;

  /**
   * @generated from field: optional string git_remote_origin = 5;
   */
  gitRemoteOrigin?: string;

  /**
   * @generated from field: optional string parse_error = 6;
   */
  parseError?: string;

  constructor(data?: PartialMessage<CursorRule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorRule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "full_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "message", T: CursorRuleType },
    { no: 4, name: "source", kind: "enum", T: proto3.getEnumType(CursorRuleSource) },
    { no: 5, name: "git_remote_origin", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "parse_error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorRule {
    return new CursorRule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorRule {
    return new CursorRule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorRule {
    return new CursorRule().fromJsonString(jsonString, options);
  }

  static equals(a: CursorRule | PlainMessage<CursorRule> | undefined, b: CursorRule | PlainMessage<CursorRule> | undefined): boolean {
    return proto3.util.equals(CursorRule, a, b);
  }
}

