// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/cursor_packages.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum agent.v1.PackageType
 */
export enum PackageType {
  /**
   * @generated from enum value: PACKAGE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PACKAGE_TYPE_CURSOR_PROJECT = 1;
   */
  CURSOR_PROJECT = 1,

  /**
   * @generated from enum value: PACKAGE_TYPE_CURSOR_PERSONAL = 2;
   */
  CURSOR_PERSONAL = 2,

  /**
   * @generated from enum value: PACKAGE_TYPE_CLAUDE_SKILL = 3;
   */
  CLAUDE_SKILL = 3,

  /**
   * @generated from enum value: PACKAGE_TYPE_CLAUDE_PLUGIN = 4;
   */
  CLAUDE_PLUGIN = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PackageType)
proto3.util.setEnumType(PackageType, "agent.v1.PackageType", [
  { no: 0, name: "PACKAGE_TYPE_UNSPECIFIED" },
  { no: 1, name: "PACKAGE_TYPE_CURSOR_PROJECT" },
  { no: 2, name: "PACKAGE_TYPE_CURSOR_PERSONAL" },
  { no: 3, name: "PACKAGE_TYPE_CLAUDE_SKILL" },
  { no: 4, name: "PACKAGE_TYPE_CLAUDE_PLUGIN" },
]);

/**
 * @generated from message agent.v1.CursorPackagePrompt
 */
export class CursorPackagePrompt extends Message<CursorPackagePrompt> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string file_path = 2;
   */
  filePath = "";

  constructor(data?: PartialMessage<CursorPackagePrompt>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorPackagePrompt";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorPackagePrompt {
    return new CursorPackagePrompt().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorPackagePrompt {
    return new CursorPackagePrompt().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorPackagePrompt {
    return new CursorPackagePrompt().fromJsonString(jsonString, options);
  }

  static equals(a: CursorPackagePrompt | PlainMessage<CursorPackagePrompt> | undefined, b: CursorPackagePrompt | PlainMessage<CursorPackagePrompt> | undefined): boolean {
    return proto3.util.equals(CursorPackagePrompt, a, b);
  }
}

/**
 * @generated from message agent.v1.CursorPackage
 */
export class CursorPackage extends Message<CursorPackage> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string folder_path = 3;
   */
  folderPath = "";

  /**
   * @generated from field: bool enabled = 4;
   */
  enabled = false;

  /**
   * @generated from field: optional string parse_error = 5;
   */
  parseError?: string;

  /**
   * @generated from field: repeated agent.v1.CursorPackagePrompt prompts = 6;
   */
  prompts: CursorPackagePrompt[] = [];

  /**
   * @generated from field: string readme_file_path = 7;
   */
  readmeFilePath = "";

  /**
   * @generated from field: agent.v1.PackageType package_type = 8;
   */
  packageType = PackageType.UNSPECIFIED;

  constructor(data?: PartialMessage<CursorPackage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CursorPackage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "folder_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "parse_error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "prompts", kind: "message", T: CursorPackagePrompt, repeated: true },
    { no: 7, name: "readme_file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "package_type", kind: "enum", T: proto3.getEnumType(PackageType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CursorPackage {
    return new CursorPackage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CursorPackage {
    return new CursorPackage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CursorPackage {
    return new CursorPackage().fromJsonString(jsonString, options);
  }

  static equals(a: CursorPackage | PlainMessage<CursorPackage> | undefined, b: CursorPackage | PlainMessage<CursorPackage> | undefined): boolean {
    return proto3.util.equals(CursorPackage, a, b);
  }
}

/**
 * @generated from message agent.v1.SkillDescriptor
 */
export class SkillDescriptor extends Message<SkillDescriptor> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string folder_path = 3;
   */
  folderPath = "";

  /**
   * @generated from field: bool enabled = 4;
   */
  enabled = false;

  /**
   * @generated from field: optional string parse_error = 5;
   */
  parseError?: string;

  /**
   * @generated from field: string readme_file_path = 6;
   */
  readmeFilePath = "";

  /**
   * @generated from field: agent.v1.PackageType package_type = 7;
   */
  packageType = PackageType.UNSPECIFIED;

  constructor(data?: PartialMessage<SkillDescriptor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SkillDescriptor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "folder_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "parse_error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "readme_file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "package_type", kind: "enum", T: proto3.getEnumType(PackageType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SkillDescriptor {
    return new SkillDescriptor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SkillDescriptor {
    return new SkillDescriptor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SkillDescriptor {
    return new SkillDescriptor().fromJsonString(jsonString, options);
  }

  static equals(a: SkillDescriptor | PlainMessage<SkillDescriptor> | undefined, b: SkillDescriptor | PlainMessage<SkillDescriptor> | undefined): boolean {
    return proto3.util.equals(SkillDescriptor, a, b);
  }
}

/**
 * @generated from message agent.v1.SkillOptions
 */
export class SkillOptions extends Message<SkillOptions> {
  /**
   * @generated from field: repeated agent.v1.SkillDescriptor skill_descriptors = 1;
   */
  skillDescriptors: SkillDescriptor[] = [];

  constructor(data?: PartialMessage<SkillOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SkillOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "skill_descriptors", kind: "message", T: SkillDescriptor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SkillOptions {
    return new SkillOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SkillOptions {
    return new SkillOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SkillOptions {
    return new SkillOptions().fromJsonString(jsonString, options);
  }

  static equals(a: SkillOptions | PlainMessage<SkillOptions> | undefined, b: SkillOptions | PlainMessage<SkillOptions> | undefined): boolean {
    return proto3.util.equals(SkillOptions, a, b);
  }
}

