// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/delete_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { DeleteArgs, DeleteResult } from "./delete_exec_pb.js";

/**
 * @generated from message agent.v1.DeleteToolCall
 */
export class DeleteToolCall extends Message<DeleteToolCall> {
  /**
   * @generated from field: agent.v1.DeleteArgs args = 1;
   */
  args?: DeleteArgs;

  /**
   * @generated from field: agent.v1.DeleteResult result = 2;
   */
  result?: DeleteResult;

  constructor(data?: PartialMessage<DeleteToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: DeleteArgs },
    { no: 2, name: "result", kind: "message", T: DeleteResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteToolCall {
    return new DeleteToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteToolCall {
    return new DeleteToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteToolCall {
    return new DeleteToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteToolCall | PlainMessage<DeleteToolCall> | undefined, b: DeleteToolCall | PlainMessage<DeleteToolCall> | undefined): boolean {
    return proto3.util.equals(DeleteToolCall, a, b);
  }
}

