// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/delete_exec.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.DeleteArgs
 */
export class DeleteArgs extends Message<DeleteArgs> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<DeleteArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteArgs {
    return new DeleteArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteArgs {
    return new DeleteArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteArgs {
    return new DeleteArgs().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteArgs | PlainMessage<DeleteArgs> | undefined, b: DeleteArgs | PlainMessage<DeleteArgs> | undefined): boolean {
    return proto3.util.equals(DeleteArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteResult
 */
export class DeleteResult extends Message<DeleteResult> {
  /**
   * @generated from oneof agent.v1.DeleteResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.DeleteSuccess success = 1;
     */
    value: DeleteSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.DeleteFileNotFound file_not_found = 2;
     */
    value: DeleteFileNotFound;
    case: "fileNotFound";
  } | {
    /**
     * @generated from field: agent.v1.DeleteNotFile not_file = 3;
     */
    value: DeleteNotFile;
    case: "notFile";
  } | {
    /**
     * @generated from field: agent.v1.DeletePermissionDenied permission_denied = 4;
     */
    value: DeletePermissionDenied;
    case: "permissionDenied";
  } | {
    /**
     * @generated from field: agent.v1.DeleteFileBusy file_busy = 5;
     */
    value: DeleteFileBusy;
    case: "fileBusy";
  } | {
    /**
     * @generated from field: agent.v1.DeleteRejected rejected = 6;
     */
    value: DeleteRejected;
    case: "rejected";
  } | {
    /**
     * @generated from field: agent.v1.DeleteError error = 7;
     */
    value: DeleteError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<DeleteResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: DeleteSuccess, oneof: "result" },
    { no: 2, name: "file_not_found", kind: "message", T: DeleteFileNotFound, oneof: "result" },
    { no: 3, name: "not_file", kind: "message", T: DeleteNotFile, oneof: "result" },
    { no: 4, name: "permission_denied", kind: "message", T: DeletePermissionDenied, oneof: "result" },
    { no: 5, name: "file_busy", kind: "message", T: DeleteFileBusy, oneof: "result" },
    { no: 6, name: "rejected", kind: "message", T: DeleteRejected, oneof: "result" },
    { no: 7, name: "error", kind: "message", T: DeleteError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResult {
    return new DeleteResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResult {
    return new DeleteResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResult {
    return new DeleteResult().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteResult | PlainMessage<DeleteResult> | undefined, b: DeleteResult | PlainMessage<DeleteResult> | undefined): boolean {
    return proto3.util.equals(DeleteResult, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteSuccess
 */
export class DeleteSuccess extends Message<DeleteSuccess> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string deleted_file = 2;
   */
  deletedFile = "";

  /**
   * @generated from field: int64 file_size = 3;
   */
  fileSize = protoInt64.zero;

  /**
   * @generated from field: string prev_content = 4;
   */
  prevContent = "";

  constructor(data?: PartialMessage<DeleteSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "deleted_file", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "prev_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSuccess {
    return new DeleteSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSuccess {
    return new DeleteSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSuccess {
    return new DeleteSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSuccess | PlainMessage<DeleteSuccess> | undefined, b: DeleteSuccess | PlainMessage<DeleteSuccess> | undefined): boolean {
    return proto3.util.equals(DeleteSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteFileNotFound
 */
export class DeleteFileNotFound extends Message<DeleteFileNotFound> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<DeleteFileNotFound>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteFileNotFound";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteFileNotFound {
    return new DeleteFileNotFound().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteFileNotFound {
    return new DeleteFileNotFound().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteFileNotFound {
    return new DeleteFileNotFound().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteFileNotFound | PlainMessage<DeleteFileNotFound> | undefined, b: DeleteFileNotFound | PlainMessage<DeleteFileNotFound> | undefined): boolean {
    return proto3.util.equals(DeleteFileNotFound, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteNotFile
 */
export class DeleteNotFile extends Message<DeleteNotFile> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string actual_type = 2;
   */
  actualType = "";

  constructor(data?: PartialMessage<DeleteNotFile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteNotFile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actual_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNotFile {
    return new DeleteNotFile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNotFile {
    return new DeleteNotFile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNotFile {
    return new DeleteNotFile().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteNotFile | PlainMessage<DeleteNotFile> | undefined, b: DeleteNotFile | PlainMessage<DeleteNotFile> | undefined): boolean {
    return proto3.util.equals(DeleteNotFile, a, b);
  }
}

/**
 * @generated from message agent.v1.DeletePermissionDenied
 */
export class DeletePermissionDenied extends Message<DeletePermissionDenied> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string client_visible_error = 2;
   */
  clientVisibleError = "";

  /**
   * @generated from field: bool is_readonly = 3;
   */
  isReadonly = false;

  constructor(data?: PartialMessage<DeletePermissionDenied>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeletePermissionDenied";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "client_visible_error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "is_readonly", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeletePermissionDenied {
    return new DeletePermissionDenied().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeletePermissionDenied {
    return new DeletePermissionDenied().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeletePermissionDenied {
    return new DeletePermissionDenied().fromJsonString(jsonString, options);
  }

  static equals(a: DeletePermissionDenied | PlainMessage<DeletePermissionDenied> | undefined, b: DeletePermissionDenied | PlainMessage<DeletePermissionDenied> | undefined): boolean {
    return proto3.util.equals(DeletePermissionDenied, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteFileBusy
 */
export class DeleteFileBusy extends Message<DeleteFileBusy> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<DeleteFileBusy>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteFileBusy";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteFileBusy {
    return new DeleteFileBusy().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteFileBusy {
    return new DeleteFileBusy().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteFileBusy {
    return new DeleteFileBusy().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteFileBusy | PlainMessage<DeleteFileBusy> | undefined, b: DeleteFileBusy | PlainMessage<DeleteFileBusy> | undefined): boolean {
    return proto3.util.equals(DeleteFileBusy, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteRejected
 */
export class DeleteRejected extends Message<DeleteRejected> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string reason = 2;
   */
  reason = "";

  constructor(data?: PartialMessage<DeleteRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRejected {
    return new DeleteRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRejected {
    return new DeleteRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRejected {
    return new DeleteRejected().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteRejected | PlainMessage<DeleteRejected> | undefined, b: DeleteRejected | PlainMessage<DeleteRejected> | undefined): boolean {
    return proto3.util.equals(DeleteRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.DeleteError
 */
export class DeleteError extends Message<DeleteError> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<DeleteError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DeleteError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteError {
    return new DeleteError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteError {
    return new DeleteError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteError {
    return new DeleteError().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteError | PlainMessage<DeleteError> | undefined, b: DeleteError | PlainMessage<DeleteError> | undefined): boolean {
    return proto3.util.equals(DeleteError, a, b);
  }
}

