// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/diagnostics_exec.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { DiagnosticSeverity, Range } from "./utils_pb.js";

/**
 * @generated from message agent.v1.DiagnosticsArgs
 */
export class DiagnosticsArgs extends Message<DiagnosticsArgs> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<DiagnosticsArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsArgs {
    return new DiagnosticsArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsArgs {
    return new DiagnosticsArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsArgs {
    return new DiagnosticsArgs().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsArgs | PlainMessage<DiagnosticsArgs> | undefined, b: DiagnosticsArgs | PlainMessage<DiagnosticsArgs> | undefined): boolean {
    return proto3.util.equals(DiagnosticsArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsResult
 */
export class DiagnosticsResult extends Message<DiagnosticsResult> {
  /**
   * @generated from oneof agent.v1.DiagnosticsResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.DiagnosticsSuccess success = 1;
     */
    value: DiagnosticsSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.DiagnosticsError error = 2;
     */
    value: DiagnosticsError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.DiagnosticsRejected rejected = 3;
     */
    value: DiagnosticsRejected;
    case: "rejected";
  } | {
    /**
     * @generated from field: agent.v1.DiagnosticsFileNotFound file_not_found = 4;
     */
    value: DiagnosticsFileNotFound;
    case: "fileNotFound";
  } | {
    /**
     * @generated from field: agent.v1.DiagnosticsPermissionDenied permission_denied = 5;
     */
    value: DiagnosticsPermissionDenied;
    case: "permissionDenied";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<DiagnosticsResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: DiagnosticsSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: DiagnosticsError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: DiagnosticsRejected, oneof: "result" },
    { no: 4, name: "file_not_found", kind: "message", T: DiagnosticsFileNotFound, oneof: "result" },
    { no: 5, name: "permission_denied", kind: "message", T: DiagnosticsPermissionDenied, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsResult {
    return new DiagnosticsResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsResult {
    return new DiagnosticsResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsResult {
    return new DiagnosticsResult().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsResult | PlainMessage<DiagnosticsResult> | undefined, b: DiagnosticsResult | PlainMessage<DiagnosticsResult> | undefined): boolean {
    return proto3.util.equals(DiagnosticsResult, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsSuccess
 */
export class DiagnosticsSuccess extends Message<DiagnosticsSuccess> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: repeated agent.v1.Diagnostic diagnostics = 2;
   */
  diagnostics: Diagnostic[] = [];

  /**
   * @generated from field: int32 total_diagnostics = 3;
   */
  totalDiagnostics = 0;

  constructor(data?: PartialMessage<DiagnosticsSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "diagnostics", kind: "message", T: Diagnostic, repeated: true },
    { no: 3, name: "total_diagnostics", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsSuccess {
    return new DiagnosticsSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsSuccess {
    return new DiagnosticsSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsSuccess {
    return new DiagnosticsSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsSuccess | PlainMessage<DiagnosticsSuccess> | undefined, b: DiagnosticsSuccess | PlainMessage<DiagnosticsSuccess> | undefined): boolean {
    return proto3.util.equals(DiagnosticsSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.Diagnostic
 */
export class Diagnostic extends Message<Diagnostic> {
  /**
   * @generated from field: agent.v1.DiagnosticSeverity severity = 1;
   */
  severity = DiagnosticSeverity.UNSPECIFIED;

  /**
   * @generated from field: agent.v1.Range range = 2;
   */
  range?: Range;

  /**
   * @generated from field: string message = 3;
   */
  message = "";

  /**
   * @generated from field: string source = 4;
   */
  source = "";

  /**
   * @generated from field: string code = 5;
   */
  code = "";

  /**
   * @generated from field: bool is_stale = 6;
   */
  isStale = false;

  constructor(data?: PartialMessage<Diagnostic>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.Diagnostic";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "severity", kind: "enum", T: proto3.getEnumType(DiagnosticSeverity) },
    { no: 2, name: "range", kind: "message", T: Range },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "is_stale", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Diagnostic {
    return new Diagnostic().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Diagnostic {
    return new Diagnostic().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Diagnostic {
    return new Diagnostic().fromJsonString(jsonString, options);
  }

  static equals(a: Diagnostic | PlainMessage<Diagnostic> | undefined, b: Diagnostic | PlainMessage<Diagnostic> | undefined): boolean {
    return proto3.util.equals(Diagnostic, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsError
 */
export class DiagnosticsError extends Message<DiagnosticsError> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<DiagnosticsError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsError {
    return new DiagnosticsError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsError {
    return new DiagnosticsError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsError {
    return new DiagnosticsError().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsError | PlainMessage<DiagnosticsError> | undefined, b: DiagnosticsError | PlainMessage<DiagnosticsError> | undefined): boolean {
    return proto3.util.equals(DiagnosticsError, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsRejected
 */
export class DiagnosticsRejected extends Message<DiagnosticsRejected> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string reason = 2;
   */
  reason = "";

  constructor(data?: PartialMessage<DiagnosticsRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsRejected {
    return new DiagnosticsRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsRejected {
    return new DiagnosticsRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsRejected {
    return new DiagnosticsRejected().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsRejected | PlainMessage<DiagnosticsRejected> | undefined, b: DiagnosticsRejected | PlainMessage<DiagnosticsRejected> | undefined): boolean {
    return proto3.util.equals(DiagnosticsRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsFileNotFound
 */
export class DiagnosticsFileNotFound extends Message<DiagnosticsFileNotFound> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<DiagnosticsFileNotFound>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsFileNotFound";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsFileNotFound {
    return new DiagnosticsFileNotFound().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsFileNotFound {
    return new DiagnosticsFileNotFound().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsFileNotFound {
    return new DiagnosticsFileNotFound().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsFileNotFound | PlainMessage<DiagnosticsFileNotFound> | undefined, b: DiagnosticsFileNotFound | PlainMessage<DiagnosticsFileNotFound> | undefined): boolean {
    return proto3.util.equals(DiagnosticsFileNotFound, a, b);
  }
}

/**
 * @generated from message agent.v1.DiagnosticsPermissionDenied
 */
export class DiagnosticsPermissionDenied extends Message<DiagnosticsPermissionDenied> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  constructor(data?: PartialMessage<DiagnosticsPermissionDenied>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DiagnosticsPermissionDenied";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DiagnosticsPermissionDenied {
    return new DiagnosticsPermissionDenied().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DiagnosticsPermissionDenied {
    return new DiagnosticsPermissionDenied().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DiagnosticsPermissionDenied {
    return new DiagnosticsPermissionDenied().fromJsonString(jsonString, options);
  }

  static equals(a: DiagnosticsPermissionDenied | PlainMessage<DiagnosticsPermissionDenied> | undefined, b: DiagnosticsPermissionDenied | PlainMessage<DiagnosticsPermissionDenied> | undefined): boolean {
    return proto3.util.equals(DiagnosticsPermissionDenied, a, b);
  }
}

