// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/exa_search_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.ExaSearchArgs
 */
export class ExaSearchArgs extends Message<ExaSearchArgs> {
  /**
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * @generated from field: int32 num_results = 3;
   */
  numResults = 0;

  /**
   * @generated from field: string tool_call_id = 4;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<ExaSearchArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "num_results", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchArgs {
    return new ExaSearchArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchArgs {
    return new ExaSearchArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchArgs {
    return new ExaSearchArgs().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchArgs | PlainMessage<ExaSearchArgs> | undefined, b: ExaSearchArgs | PlainMessage<ExaSearchArgs> | undefined): boolean {
    return proto3.util.equals(ExaSearchArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchResult
 */
export class ExaSearchResult extends Message<ExaSearchResult> {
  /**
   * @generated from oneof agent.v1.ExaSearchResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ExaSearchSuccess success = 1;
     */
    value: ExaSearchSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.ExaSearchError error = 2;
     */
    value: ExaSearchError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.ExaSearchRejected rejected = 3;
     */
    value: ExaSearchRejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ExaSearchResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: ExaSearchSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: ExaSearchError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: ExaSearchRejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchResult {
    return new ExaSearchResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchResult {
    return new ExaSearchResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchResult {
    return new ExaSearchResult().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchResult | PlainMessage<ExaSearchResult> | undefined, b: ExaSearchResult | PlainMessage<ExaSearchResult> | undefined): boolean {
    return proto3.util.equals(ExaSearchResult, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchSuccess
 */
export class ExaSearchSuccess extends Message<ExaSearchSuccess> {
  /**
   * @generated from field: repeated agent.v1.ExaSearchReference references = 1;
   */
  references: ExaSearchReference[] = [];

  constructor(data?: PartialMessage<ExaSearchSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "references", kind: "message", T: ExaSearchReference, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchSuccess {
    return new ExaSearchSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchSuccess {
    return new ExaSearchSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchSuccess {
    return new ExaSearchSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchSuccess | PlainMessage<ExaSearchSuccess> | undefined, b: ExaSearchSuccess | PlainMessage<ExaSearchSuccess> | undefined): boolean {
    return proto3.util.equals(ExaSearchSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchError
 */
export class ExaSearchError extends Message<ExaSearchError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<ExaSearchError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchError {
    return new ExaSearchError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchError {
    return new ExaSearchError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchError {
    return new ExaSearchError().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchError | PlainMessage<ExaSearchError> | undefined, b: ExaSearchError | PlainMessage<ExaSearchError> | undefined): boolean {
    return proto3.util.equals(ExaSearchError, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchRejected
 */
export class ExaSearchRejected extends Message<ExaSearchRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<ExaSearchRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchRejected {
    return new ExaSearchRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchRejected {
    return new ExaSearchRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchRejected {
    return new ExaSearchRejected().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchRejected | PlainMessage<ExaSearchRejected> | undefined, b: ExaSearchRejected | PlainMessage<ExaSearchRejected> | undefined): boolean {
    return proto3.util.equals(ExaSearchRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchReference
 */
export class ExaSearchReference extends Message<ExaSearchReference> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string url = 2;
   */
  url = "";

  /**
   * @generated from field: string text = 3;
   */
  text = "";

  /**
   * @generated from field: string published_date = 4;
   */
  publishedDate = "";

  constructor(data?: PartialMessage<ExaSearchReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "published_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchReference {
    return new ExaSearchReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchReference {
    return new ExaSearchReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchReference {
    return new ExaSearchReference().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchReference | PlainMessage<ExaSearchReference> | undefined, b: ExaSearchReference | PlainMessage<ExaSearchReference> | undefined): boolean {
    return proto3.util.equals(ExaSearchReference, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchToolCall
 */
export class ExaSearchToolCall extends Message<ExaSearchToolCall> {
  /**
   * @generated from field: agent.v1.ExaSearchArgs args = 1;
   */
  args?: ExaSearchArgs;

  /**
   * @generated from field: agent.v1.ExaSearchResult result = 2;
   */
  result?: ExaSearchResult;

  constructor(data?: PartialMessage<ExaSearchToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ExaSearchArgs },
    { no: 2, name: "result", kind: "message", T: ExaSearchResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchToolCall {
    return new ExaSearchToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchToolCall {
    return new ExaSearchToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchToolCall {
    return new ExaSearchToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchToolCall | PlainMessage<ExaSearchToolCall> | undefined, b: ExaSearchToolCall | PlainMessage<ExaSearchToolCall> | undefined): boolean {
    return proto3.util.equals(ExaSearchToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchRequestQuery
 */
export class ExaSearchRequestQuery extends Message<ExaSearchRequestQuery> {
  /**
   * @generated from field: agent.v1.ExaSearchArgs args = 1;
   */
  args?: ExaSearchArgs;

  constructor(data?: PartialMessage<ExaSearchRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ExaSearchArgs },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchRequestQuery {
    return new ExaSearchRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchRequestQuery {
    return new ExaSearchRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchRequestQuery {
    return new ExaSearchRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchRequestQuery | PlainMessage<ExaSearchRequestQuery> | undefined, b: ExaSearchRequestQuery | PlainMessage<ExaSearchRequestQuery> | undefined): boolean {
    return proto3.util.equals(ExaSearchRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchRequestResponse
 */
export class ExaSearchRequestResponse extends Message<ExaSearchRequestResponse> {
  /**
   * @generated from oneof agent.v1.ExaSearchRequestResponse.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ExaSearchRequestResponse_Approved approved = 1;
     */
    value: ExaSearchRequestResponse_Approved;
    case: "approved";
  } | {
    /**
     * @generated from field: agent.v1.ExaSearchRequestResponse_Rejected rejected = 2;
     */
    value: ExaSearchRequestResponse_Rejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ExaSearchRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "approved", kind: "message", T: ExaSearchRequestResponse_Approved, oneof: "result" },
    { no: 2, name: "rejected", kind: "message", T: ExaSearchRequestResponse_Rejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchRequestResponse {
    return new ExaSearchRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse {
    return new ExaSearchRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse {
    return new ExaSearchRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchRequestResponse | PlainMessage<ExaSearchRequestResponse> | undefined, b: ExaSearchRequestResponse | PlainMessage<ExaSearchRequestResponse> | undefined): boolean {
    return proto3.util.equals(ExaSearchRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchRequestResponse_Approved
 */
export class ExaSearchRequestResponse_Approved extends Message<ExaSearchRequestResponse_Approved> {
  constructor(data?: PartialMessage<ExaSearchRequestResponse_Approved>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchRequestResponse_Approved";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchRequestResponse_Approved {
    return new ExaSearchRequestResponse_Approved().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse_Approved {
    return new ExaSearchRequestResponse_Approved().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse_Approved {
    return new ExaSearchRequestResponse_Approved().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchRequestResponse_Approved | PlainMessage<ExaSearchRequestResponse_Approved> | undefined, b: ExaSearchRequestResponse_Approved | PlainMessage<ExaSearchRequestResponse_Approved> | undefined): boolean {
    return proto3.util.equals(ExaSearchRequestResponse_Approved, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaSearchRequestResponse_Rejected
 */
export class ExaSearchRequestResponse_Rejected extends Message<ExaSearchRequestResponse_Rejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<ExaSearchRequestResponse_Rejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaSearchRequestResponse_Rejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaSearchRequestResponse_Rejected {
    return new ExaSearchRequestResponse_Rejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse_Rejected {
    return new ExaSearchRequestResponse_Rejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaSearchRequestResponse_Rejected {
    return new ExaSearchRequestResponse_Rejected().fromJsonString(jsonString, options);
  }

  static equals(a: ExaSearchRequestResponse_Rejected | PlainMessage<ExaSearchRequestResponse_Rejected> | undefined, b: ExaSearchRequestResponse_Rejected | PlainMessage<ExaSearchRequestResponse_Rejected> | undefined): boolean {
    return proto3.util.equals(ExaSearchRequestResponse_Rejected, a, b);
  }
}

