// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/exa_fetch_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.ExaFetchArgs
 */
export class ExaFetchArgs extends Message<ExaFetchArgs> {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[] = [];

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<ExaFetchArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchArgs {
    return new ExaFetchArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchArgs {
    return new ExaFetchArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchArgs {
    return new ExaFetchArgs().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchArgs | PlainMessage<ExaFetchArgs> | undefined, b: ExaFetchArgs | PlainMessage<ExaFetchArgs> | undefined): boolean {
    return proto3.util.equals(ExaFetchArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchResult
 */
export class ExaFetchResult extends Message<ExaFetchResult> {
  /**
   * @generated from oneof agent.v1.ExaFetchResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ExaFetchSuccess success = 1;
     */
    value: ExaFetchSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.ExaFetchError error = 2;
     */
    value: ExaFetchError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.ExaFetchRejected rejected = 3;
     */
    value: ExaFetchRejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ExaFetchResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: ExaFetchSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: ExaFetchError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: ExaFetchRejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchResult {
    return new ExaFetchResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchResult {
    return new ExaFetchResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchResult {
    return new ExaFetchResult().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchResult | PlainMessage<ExaFetchResult> | undefined, b: ExaFetchResult | PlainMessage<ExaFetchResult> | undefined): boolean {
    return proto3.util.equals(ExaFetchResult, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchSuccess
 */
export class ExaFetchSuccess extends Message<ExaFetchSuccess> {
  /**
   * @generated from field: repeated agent.v1.ExaFetchContent contents = 1;
   */
  contents: ExaFetchContent[] = [];

  constructor(data?: PartialMessage<ExaFetchSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contents", kind: "message", T: ExaFetchContent, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchSuccess {
    return new ExaFetchSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchSuccess {
    return new ExaFetchSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchSuccess {
    return new ExaFetchSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchSuccess | PlainMessage<ExaFetchSuccess> | undefined, b: ExaFetchSuccess | PlainMessage<ExaFetchSuccess> | undefined): boolean {
    return proto3.util.equals(ExaFetchSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchError
 */
export class ExaFetchError extends Message<ExaFetchError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<ExaFetchError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchError {
    return new ExaFetchError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchError {
    return new ExaFetchError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchError {
    return new ExaFetchError().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchError | PlainMessage<ExaFetchError> | undefined, b: ExaFetchError | PlainMessage<ExaFetchError> | undefined): boolean {
    return proto3.util.equals(ExaFetchError, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchRejected
 */
export class ExaFetchRejected extends Message<ExaFetchRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<ExaFetchRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchRejected {
    return new ExaFetchRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchRejected {
    return new ExaFetchRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchRejected {
    return new ExaFetchRejected().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchRejected | PlainMessage<ExaFetchRejected> | undefined, b: ExaFetchRejected | PlainMessage<ExaFetchRejected> | undefined): boolean {
    return proto3.util.equals(ExaFetchRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchContent
 */
export class ExaFetchContent extends Message<ExaFetchContent> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string url = 2;
   */
  url = "";

  /**
   * @generated from field: string text = 3;
   */
  text = "";

  /**
   * @generated from field: string published_date = 4;
   */
  publishedDate = "";

  constructor(data?: PartialMessage<ExaFetchContent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchContent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "published_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchContent {
    return new ExaFetchContent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchContent {
    return new ExaFetchContent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchContent {
    return new ExaFetchContent().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchContent | PlainMessage<ExaFetchContent> | undefined, b: ExaFetchContent | PlainMessage<ExaFetchContent> | undefined): boolean {
    return proto3.util.equals(ExaFetchContent, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchToolCall
 */
export class ExaFetchToolCall extends Message<ExaFetchToolCall> {
  /**
   * @generated from field: agent.v1.ExaFetchArgs args = 1;
   */
  args?: ExaFetchArgs;

  /**
   * @generated from field: agent.v1.ExaFetchResult result = 2;
   */
  result?: ExaFetchResult;

  constructor(data?: PartialMessage<ExaFetchToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ExaFetchArgs },
    { no: 2, name: "result", kind: "message", T: ExaFetchResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchToolCall {
    return new ExaFetchToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchToolCall {
    return new ExaFetchToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchToolCall {
    return new ExaFetchToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchToolCall | PlainMessage<ExaFetchToolCall> | undefined, b: ExaFetchToolCall | PlainMessage<ExaFetchToolCall> | undefined): boolean {
    return proto3.util.equals(ExaFetchToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchRequestQuery
 */
export class ExaFetchRequestQuery extends Message<ExaFetchRequestQuery> {
  /**
   * @generated from field: agent.v1.ExaFetchArgs args = 1;
   */
  args?: ExaFetchArgs;

  constructor(data?: PartialMessage<ExaFetchRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ExaFetchArgs },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchRequestQuery {
    return new ExaFetchRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchRequestQuery {
    return new ExaFetchRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchRequestQuery {
    return new ExaFetchRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchRequestQuery | PlainMessage<ExaFetchRequestQuery> | undefined, b: ExaFetchRequestQuery | PlainMessage<ExaFetchRequestQuery> | undefined): boolean {
    return proto3.util.equals(ExaFetchRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchRequestResponse
 */
export class ExaFetchRequestResponse extends Message<ExaFetchRequestResponse> {
  /**
   * @generated from oneof agent.v1.ExaFetchRequestResponse.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ExaFetchRequestResponse_Approved approved = 1;
     */
    value: ExaFetchRequestResponse_Approved;
    case: "approved";
  } | {
    /**
     * @generated from field: agent.v1.ExaFetchRequestResponse_Rejected rejected = 2;
     */
    value: ExaFetchRequestResponse_Rejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ExaFetchRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "approved", kind: "message", T: ExaFetchRequestResponse_Approved, oneof: "result" },
    { no: 2, name: "rejected", kind: "message", T: ExaFetchRequestResponse_Rejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchRequestResponse {
    return new ExaFetchRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse {
    return new ExaFetchRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse {
    return new ExaFetchRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchRequestResponse | PlainMessage<ExaFetchRequestResponse> | undefined, b: ExaFetchRequestResponse | PlainMessage<ExaFetchRequestResponse> | undefined): boolean {
    return proto3.util.equals(ExaFetchRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchRequestResponse_Approved
 */
export class ExaFetchRequestResponse_Approved extends Message<ExaFetchRequestResponse_Approved> {
  constructor(data?: PartialMessage<ExaFetchRequestResponse_Approved>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchRequestResponse_Approved";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchRequestResponse_Approved {
    return new ExaFetchRequestResponse_Approved().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse_Approved {
    return new ExaFetchRequestResponse_Approved().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse_Approved {
    return new ExaFetchRequestResponse_Approved().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchRequestResponse_Approved | PlainMessage<ExaFetchRequestResponse_Approved> | undefined, b: ExaFetchRequestResponse_Approved | PlainMessage<ExaFetchRequestResponse_Approved> | undefined): boolean {
    return proto3.util.equals(ExaFetchRequestResponse_Approved, a, b);
  }
}

/**
 * @generated from message agent.v1.ExaFetchRequestResponse_Rejected
 */
export class ExaFetchRequestResponse_Rejected extends Message<ExaFetchRequestResponse_Rejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<ExaFetchRequestResponse_Rejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ExaFetchRequestResponse_Rejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExaFetchRequestResponse_Rejected {
    return new ExaFetchRequestResponse_Rejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse_Rejected {
    return new ExaFetchRequestResponse_Rejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExaFetchRequestResponse_Rejected {
    return new ExaFetchRequestResponse_Rejected().fromJsonString(jsonString, options);
  }

  static equals(a: ExaFetchRequestResponse_Rejected | PlainMessage<ExaFetchRequestResponse_Rejected> | undefined, b: ExaFetchRequestResponse_Rejected | PlainMessage<ExaFetchRequestResponse_Rejected> | undefined): boolean {
    return proto3.util.equals(ExaFetchRequestResponse_Rejected, a, b);
  }
}

