// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file agent/v1/exec_service.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service agent.v1.ExecService
 */
export const ExecService = {
  typeName: "agent.v1.ExecService",
  methods: {
  }
} as const;

