// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/generate_image_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.GenerateImageArgs
 */
export class GenerateImageArgs extends Message<GenerateImageArgs> {
  /**
   * @generated from field: string description = 1;
   */
  description = "";

  /**
   * @generated from field: optional string file_path = 2;
   */
  filePath?: string;

  /**
   * @generated from field: repeated string reference_image_paths = 5;
   */
  referenceImagePaths: string[] = [];

  constructor(data?: PartialMessage<GenerateImageArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GenerateImageArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "file_path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "reference_image_paths", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateImageArgs {
    return new GenerateImageArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateImageArgs {
    return new GenerateImageArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateImageArgs {
    return new GenerateImageArgs().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateImageArgs | PlainMessage<GenerateImageArgs> | undefined, b: GenerateImageArgs | PlainMessage<GenerateImageArgs> | undefined): boolean {
    return proto3.util.equals(GenerateImageArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.GenerateImageResult
 */
export class GenerateImageResult extends Message<GenerateImageResult> {
  /**
   * @generated from oneof agent.v1.GenerateImageResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.GenerateImageSuccess success = 1;
     */
    value: GenerateImageSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.GenerateImageError error = 2;
     */
    value: GenerateImageError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GenerateImageResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GenerateImageResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: GenerateImageSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: GenerateImageError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateImageResult {
    return new GenerateImageResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateImageResult {
    return new GenerateImageResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateImageResult {
    return new GenerateImageResult().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateImageResult | PlainMessage<GenerateImageResult> | undefined, b: GenerateImageResult | PlainMessage<GenerateImageResult> | undefined): boolean {
    return proto3.util.equals(GenerateImageResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GenerateImageSuccess
 */
export class GenerateImageSuccess extends Message<GenerateImageSuccess> {
  /**
   * @generated from field: string file_path = 1;
   */
  filePath = "";

  /**
   * @generated from field: string image_data = 2;
   */
  imageData = "";

  constructor(data?: PartialMessage<GenerateImageSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GenerateImageSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image_data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateImageSuccess {
    return new GenerateImageSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateImageSuccess {
    return new GenerateImageSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateImageSuccess {
    return new GenerateImageSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateImageSuccess | PlainMessage<GenerateImageSuccess> | undefined, b: GenerateImageSuccess | PlainMessage<GenerateImageSuccess> | undefined): boolean {
    return proto3.util.equals(GenerateImageSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.GenerateImageError
 */
export class GenerateImageError extends Message<GenerateImageError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<GenerateImageError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GenerateImageError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateImageError {
    return new GenerateImageError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateImageError {
    return new GenerateImageError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateImageError {
    return new GenerateImageError().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateImageError | PlainMessage<GenerateImageError> | undefined, b: GenerateImageError | PlainMessage<GenerateImageError> | undefined): boolean {
    return proto3.util.equals(GenerateImageError, a, b);
  }
}

/**
 * @generated from message agent.v1.GenerateImageToolCall
 */
export class GenerateImageToolCall extends Message<GenerateImageToolCall> {
  /**
   * @generated from field: agent.v1.GenerateImageArgs args = 1;
   */
  args?: GenerateImageArgs;

  /**
   * @generated from field: agent.v1.GenerateImageResult result = 2;
   */
  result?: GenerateImageResult;

  constructor(data?: PartialMessage<GenerateImageToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GenerateImageToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: GenerateImageArgs },
    { no: 2, name: "result", kind: "message", T: GenerateImageResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateImageToolCall {
    return new GenerateImageToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateImageToolCall {
    return new GenerateImageToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateImageToolCall {
    return new GenerateImageToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateImageToolCall | PlainMessage<GenerateImageToolCall> | undefined, b: GenerateImageToolCall | PlainMessage<GenerateImageToolCall> | undefined): boolean {
    return proto3.util.equals(GenerateImageToolCall, a, b);
  }
}

