// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/glob_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.GlobToolResult
 */
export class GlobToolResult extends Message<GlobToolResult> {
  /**
   * @generated from oneof agent.v1.GlobToolResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.GlobToolSuccess success = 1;
     */
    value: GlobToolSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.GlobToolError error = 2;
     */
    value: GlobToolError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GlobToolResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GlobToolResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: GlobToolSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: GlobToolError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobToolResult {
    return new GlobToolResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobToolResult {
    return new GlobToolResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobToolResult {
    return new GlobToolResult().fromJsonString(jsonString, options);
  }

  static equals(a: GlobToolResult | PlainMessage<GlobToolResult> | undefined, b: GlobToolResult | PlainMessage<GlobToolResult> | undefined): boolean {
    return proto3.util.equals(GlobToolResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GlobToolError
 */
export class GlobToolError extends Message<GlobToolError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<GlobToolError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GlobToolError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobToolError {
    return new GlobToolError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobToolError {
    return new GlobToolError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobToolError {
    return new GlobToolError().fromJsonString(jsonString, options);
  }

  static equals(a: GlobToolError | PlainMessage<GlobToolError> | undefined, b: GlobToolError | PlainMessage<GlobToolError> | undefined): boolean {
    return proto3.util.equals(GlobToolError, a, b);
  }
}

/**
 * @generated from message agent.v1.GlobToolSuccess
 */
export class GlobToolSuccess extends Message<GlobToolSuccess> {
  /**
   * @generated from field: string pattern = 1;
   */
  pattern = "";

  /**
   * @generated from field: string path = 2;
   */
  path = "";

  /**
   * @generated from field: repeated string files = 3;
   */
  files: string[] = [];

  /**
   * @generated from field: int32 total_files = 4;
   */
  totalFiles = 0;

  /**
   * @generated from field: bool client_truncated = 5;
   */
  clientTruncated = false;

  /**
   * @generated from field: bool ripgrep_truncated = 6;
   */
  ripgrepTruncated = false;

  constructor(data?: PartialMessage<GlobToolSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GlobToolSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "files", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "total_files", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "client_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "ripgrep_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobToolSuccess {
    return new GlobToolSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobToolSuccess {
    return new GlobToolSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobToolSuccess {
    return new GlobToolSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: GlobToolSuccess | PlainMessage<GlobToolSuccess> | undefined, b: GlobToolSuccess | PlainMessage<GlobToolSuccess> | undefined): boolean {
    return proto3.util.equals(GlobToolSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.GlobToolArgs
 */
export class GlobToolArgs extends Message<GlobToolArgs> {
  /**
   * @generated from field: optional string target_directory = 1;
   */
  targetDirectory?: string;

  /**
   * @generated from field: string glob_pattern = 2;
   */
  globPattern = "";

  constructor(data?: PartialMessage<GlobToolArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GlobToolArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_directory", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "glob_pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobToolArgs {
    return new GlobToolArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobToolArgs {
    return new GlobToolArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobToolArgs {
    return new GlobToolArgs().fromJsonString(jsonString, options);
  }

  static equals(a: GlobToolArgs | PlainMessage<GlobToolArgs> | undefined, b: GlobToolArgs | PlainMessage<GlobToolArgs> | undefined): boolean {
    return proto3.util.equals(GlobToolArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.GlobToolCall
 */
export class GlobToolCall extends Message<GlobToolCall> {
  /**
   * @generated from field: agent.v1.GlobToolArgs args = 1;
   */
  args?: GlobToolArgs;

  /**
   * @generated from field: agent.v1.GlobToolResult result = 2;
   */
  result?: GlobToolResult;

  constructor(data?: PartialMessage<GlobToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GlobToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: GlobToolArgs },
    { no: 2, name: "result", kind: "message", T: GlobToolResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobToolCall {
    return new GlobToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobToolCall {
    return new GlobToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobToolCall {
    return new GlobToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: GlobToolCall | PlainMessage<GlobToolCall> | undefined, b: GlobToolCall | PlainMessage<GlobToolCall> | undefined): boolean {
    return proto3.util.equals(GlobToolCall, a, b);
  }
}

