// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/grep_exec.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { SandboxPolicy } from "./sandbox_pb.js";

/**
 * @generated from message agent.v1.GrepArgs
 */
export class GrepArgs extends Message<GrepArgs> {
  /**
   * @generated from field: string pattern = 1;
   */
  pattern = "";

  /**
   * @generated from field: optional string path = 2;
   */
  path?: string;

  /**
   * @generated from field: optional string glob = 3;
   */
  glob?: string;

  /**
   * @generated from field: optional string output_mode = 4;
   */
  outputMode?: string;

  /**
   * @generated from field: optional int32 context_before = 5;
   */
  contextBefore?: number;

  /**
   * @generated from field: optional int32 context_after = 6;
   */
  contextAfter?: number;

  /**
   * @generated from field: optional int32 context = 7;
   */
  context?: number;

  /**
   * @generated from field: optional bool case_insensitive = 8;
   */
  caseInsensitive?: boolean;

  /**
   * @generated from field: optional string type = 9;
   */
  type?: string;

  /**
   * @generated from field: optional int32 head_limit = 10;
   */
  headLimit?: number;

  /**
   * @generated from field: optional bool multiline = 11;
   */
  multiline?: boolean;

  /**
   * @generated from field: optional string sort = 12;
   */
  sort?: string;

  /**
   * @generated from field: optional bool sort_ascending = 13;
   */
  sortAscending?: boolean;

  /**
   * @generated from field: string tool_call_id = 14;
   */
  toolCallId = "";

  /**
   * @generated from field: optional agent.v1.SandboxPolicy sandbox_policy = 15;
   */
  sandboxPolicy?: SandboxPolicy;

  constructor(data?: PartialMessage<GrepArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "glob", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "output_mode", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "context_before", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "context_after", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 7, name: "context", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 8, name: "case_insensitive", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 9, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "head_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 11, name: "multiline", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 12, name: "sort", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "sort_ascending", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 14, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "sandbox_policy", kind: "message", T: SandboxPolicy, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepArgs {
    return new GrepArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepArgs {
    return new GrepArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepArgs {
    return new GrepArgs().fromJsonString(jsonString, options);
  }

  static equals(a: GrepArgs | PlainMessage<GrepArgs> | undefined, b: GrepArgs | PlainMessage<GrepArgs> | undefined): boolean {
    return proto3.util.equals(GrepArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepResult
 */
export class GrepResult extends Message<GrepResult> {
  /**
   * @generated from oneof agent.v1.GrepResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.GrepSuccess success = 1;
     */
    value: GrepSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.GrepError error = 2;
     */
    value: GrepError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GrepResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: GrepSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: GrepError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepResult {
    return new GrepResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepResult {
    return new GrepResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepResult {
    return new GrepResult().fromJsonString(jsonString, options);
  }

  static equals(a: GrepResult | PlainMessage<GrepResult> | undefined, b: GrepResult | PlainMessage<GrepResult> | undefined): boolean {
    return proto3.util.equals(GrepResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepError
 */
export class GrepError extends Message<GrepError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<GrepError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepError {
    return new GrepError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepError {
    return new GrepError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepError {
    return new GrepError().fromJsonString(jsonString, options);
  }

  static equals(a: GrepError | PlainMessage<GrepError> | undefined, b: GrepError | PlainMessage<GrepError> | undefined): boolean {
    return proto3.util.equals(GrepError, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepSuccess
 */
export class GrepSuccess extends Message<GrepSuccess> {
  /**
   * @generated from field: string pattern = 1;
   */
  pattern = "";

  /**
   * @generated from field: string path = 2;
   */
  path = "";

  /**
   * @generated from field: string output_mode = 3;
   */
  outputMode = "";

  /**
   * @generated from field: map<string, agent.v1.GrepUnionResult> workspace_results = 4;
   */
  workspaceResults: { [key: string]: GrepUnionResult } = {};

  /**
   * @generated from field: optional agent.v1.GrepUnionResult active_editor_result = 5;
   */
  activeEditorResult?: GrepUnionResult;

  constructor(data?: PartialMessage<GrepSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "output_mode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "workspace_results", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: GrepUnionResult} },
    { no: 5, name: "active_editor_result", kind: "message", T: GrepUnionResult, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepSuccess {
    return new GrepSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepSuccess {
    return new GrepSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepSuccess {
    return new GrepSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: GrepSuccess | PlainMessage<GrepSuccess> | undefined, b: GrepSuccess | PlainMessage<GrepSuccess> | undefined): boolean {
    return proto3.util.equals(GrepSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepUnionResult
 */
export class GrepUnionResult extends Message<GrepUnionResult> {
  /**
   * @generated from oneof agent.v1.GrepUnionResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.GrepCountResult count = 1;
     */
    value: GrepCountResult;
    case: "count";
  } | {
    /**
     * @generated from field: agent.v1.GrepFilesResult files = 2;
     */
    value: GrepFilesResult;
    case: "files";
  } | {
    /**
     * @generated from field: agent.v1.GrepContentResult content = 3;
     */
    value: GrepContentResult;
    case: "content";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GrepUnionResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepUnionResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "count", kind: "message", T: GrepCountResult, oneof: "result" },
    { no: 2, name: "files", kind: "message", T: GrepFilesResult, oneof: "result" },
    { no: 3, name: "content", kind: "message", T: GrepContentResult, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepUnionResult {
    return new GrepUnionResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepUnionResult {
    return new GrepUnionResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepUnionResult {
    return new GrepUnionResult().fromJsonString(jsonString, options);
  }

  static equals(a: GrepUnionResult | PlainMessage<GrepUnionResult> | undefined, b: GrepUnionResult | PlainMessage<GrepUnionResult> | undefined): boolean {
    return proto3.util.equals(GrepUnionResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepCountResult
 */
export class GrepCountResult extends Message<GrepCountResult> {
  /**
   * @generated from field: repeated agent.v1.GrepFileCount counts = 1;
   */
  counts: GrepFileCount[] = [];

  /**
   * @generated from field: int32 total_files = 2;
   */
  totalFiles = 0;

  /**
   * @generated from field: int32 total_matches = 3;
   */
  totalMatches = 0;

  /**
   * @generated from field: bool client_truncated = 4;
   */
  clientTruncated = false;

  /**
   * @generated from field: bool ripgrep_truncated = 5;
   */
  ripgrepTruncated = false;

  constructor(data?: PartialMessage<GrepCountResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepCountResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "counts", kind: "message", T: GrepFileCount, repeated: true },
    { no: 2, name: "total_files", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "total_matches", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "client_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "ripgrep_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepCountResult {
    return new GrepCountResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepCountResult {
    return new GrepCountResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepCountResult {
    return new GrepCountResult().fromJsonString(jsonString, options);
  }

  static equals(a: GrepCountResult | PlainMessage<GrepCountResult> | undefined, b: GrepCountResult | PlainMessage<GrepCountResult> | undefined): boolean {
    return proto3.util.equals(GrepCountResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepFileCount
 */
export class GrepFileCount extends Message<GrepFileCount> {
  /**
   * @generated from field: string file = 1;
   */
  file = "";

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  constructor(data?: PartialMessage<GrepFileCount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepFileCount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepFileCount {
    return new GrepFileCount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepFileCount {
    return new GrepFileCount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepFileCount {
    return new GrepFileCount().fromJsonString(jsonString, options);
  }

  static equals(a: GrepFileCount | PlainMessage<GrepFileCount> | undefined, b: GrepFileCount | PlainMessage<GrepFileCount> | undefined): boolean {
    return proto3.util.equals(GrepFileCount, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepFilesResult
 */
export class GrepFilesResult extends Message<GrepFilesResult> {
  /**
   * @generated from field: repeated string files = 1;
   */
  files: string[] = [];

  /**
   * @generated from field: int32 total_files = 2;
   */
  totalFiles = 0;

  /**
   * @generated from field: bool client_truncated = 3;
   */
  clientTruncated = false;

  /**
   * @generated from field: bool ripgrep_truncated = 4;
   */
  ripgrepTruncated = false;

  constructor(data?: PartialMessage<GrepFilesResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepFilesResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "files", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "total_files", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "client_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "ripgrep_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepFilesResult {
    return new GrepFilesResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepFilesResult {
    return new GrepFilesResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepFilesResult {
    return new GrepFilesResult().fromJsonString(jsonString, options);
  }

  static equals(a: GrepFilesResult | PlainMessage<GrepFilesResult> | undefined, b: GrepFilesResult | PlainMessage<GrepFilesResult> | undefined): boolean {
    return proto3.util.equals(GrepFilesResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepContentResult
 */
export class GrepContentResult extends Message<GrepContentResult> {
  /**
   * @generated from field: repeated agent.v1.GrepFileMatch matches = 1;
   */
  matches: GrepFileMatch[] = [];

  /**
   * @generated from field: int32 total_lines = 2;
   */
  totalLines = 0;

  /**
   * @generated from field: int32 total_matched_lines = 3;
   */
  totalMatchedLines = 0;

  /**
   * @generated from field: bool client_truncated = 4;
   */
  clientTruncated = false;

  /**
   * @generated from field: bool ripgrep_truncated = 5;
   */
  ripgrepTruncated = false;

  constructor(data?: PartialMessage<GrepContentResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepContentResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "matches", kind: "message", T: GrepFileMatch, repeated: true },
    { no: 2, name: "total_lines", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "total_matched_lines", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "client_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "ripgrep_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepContentResult {
    return new GrepContentResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepContentResult {
    return new GrepContentResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepContentResult {
    return new GrepContentResult().fromJsonString(jsonString, options);
  }

  static equals(a: GrepContentResult | PlainMessage<GrepContentResult> | undefined, b: GrepContentResult | PlainMessage<GrepContentResult> | undefined): boolean {
    return proto3.util.equals(GrepContentResult, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepFileMatch
 */
export class GrepFileMatch extends Message<GrepFileMatch> {
  /**
   * @generated from field: string file = 1;
   */
  file = "";

  /**
   * @generated from field: repeated agent.v1.GrepContentMatch matches = 2;
   */
  matches: GrepContentMatch[] = [];

  constructor(data?: PartialMessage<GrepFileMatch>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepFileMatch";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "matches", kind: "message", T: GrepContentMatch, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepFileMatch {
    return new GrepFileMatch().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepFileMatch {
    return new GrepFileMatch().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepFileMatch {
    return new GrepFileMatch().fromJsonString(jsonString, options);
  }

  static equals(a: GrepFileMatch | PlainMessage<GrepFileMatch> | undefined, b: GrepFileMatch | PlainMessage<GrepFileMatch> | undefined): boolean {
    return proto3.util.equals(GrepFileMatch, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepContentMatch
 */
export class GrepContentMatch extends Message<GrepContentMatch> {
  /**
   * @generated from field: int32 line_number = 1;
   */
  lineNumber = 0;

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: bool content_truncated = 3;
   */
  contentTruncated = false;

  /**
   * @generated from field: bool is_context_line = 4;
   */
  isContextLine = false;

  constructor(data?: PartialMessage<GrepContentMatch>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepContentMatch";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "line_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content_truncated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "is_context_line", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepContentMatch {
    return new GrepContentMatch().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepContentMatch {
    return new GrepContentMatch().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepContentMatch {
    return new GrepContentMatch().fromJsonString(jsonString, options);
  }

  static equals(a: GrepContentMatch | PlainMessage<GrepContentMatch> | undefined, b: GrepContentMatch | PlainMessage<GrepContentMatch> | undefined): boolean {
    return proto3.util.equals(GrepContentMatch, a, b);
  }
}

/**
 * @generated from message agent.v1.GrepStream
 */
export class GrepStream extends Message<GrepStream> {
  /**
   * @generated from field: string pattern = 1;
   */
  pattern = "";

  constructor(data?: PartialMessage<GrepStream>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GrepStream";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrepStream {
    return new GrepStream().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrepStream {
    return new GrepStream().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrepStream {
    return new GrepStream().fromJsonString(jsonString, options);
  }

  static equals(a: GrepStream | PlainMessage<GrepStream> | undefined, b: GrepStream | PlainMessage<GrepStream> | undefined): boolean {
    return proto3.util.equals(GrepStream, a, b);
  }
}

