// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/ls_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { LsArgs, LsResult } from "./ls_exec_pb.js";

/**
 * @generated from message agent.v1.LsToolCall
 */
export class LsToolCall extends Message<LsToolCall> {
  /**
   * @generated from field: agent.v1.LsArgs args = 1;
   */
  args?: LsArgs;

  /**
   * @generated from field: agent.v1.LsResult result = 2;
   */
  result?: LsResult;

  constructor(data?: PartialMessage<LsToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.LsToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: LsArgs },
    { no: 2, name: "result", kind: "message", T: LsResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LsToolCall {
    return new LsToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LsToolCall {
    return new LsToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LsToolCall {
    return new LsToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: LsToolCall | PlainMessage<LsToolCall> | undefined, b: LsToolCall | PlainMessage<LsToolCall> | undefined): boolean {
    return proto3.util.equals(LsToolCall, a, b);
  }
}

