// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/mcp.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.McpToolDefinition
 */
export class McpToolDefinition extends Message<McpToolDefinition> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string provider_identifier = 4;
   */
  providerIdentifier = "";

  /**
   * @generated from field: string tool_name = 5;
   */
  toolName = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: bytes input_schema = 3;
   */
  inputSchema = new Uint8Array(0);

  constructor(data?: PartialMessage<McpToolDefinition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpToolDefinition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "provider_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tool_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "input_schema", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpToolDefinition {
    return new McpToolDefinition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpToolDefinition {
    return new McpToolDefinition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpToolDefinition {
    return new McpToolDefinition().fromJsonString(jsonString, options);
  }

  static equals(a: McpToolDefinition | PlainMessage<McpToolDefinition> | undefined, b: McpToolDefinition | PlainMessage<McpToolDefinition> | undefined): boolean {
    return proto3.util.equals(McpToolDefinition, a, b);
  }
}

/**
 * @generated from message agent.v1.McpTools
 */
export class McpTools extends Message<McpTools> {
  /**
   * @generated from field: repeated agent.v1.McpToolDefinition mcp_tools = 1;
   */
  mcpTools: McpToolDefinition[] = [];

  constructor(data?: PartialMessage<McpTools>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpTools";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mcp_tools", kind: "message", T: McpToolDefinition, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpTools {
    return new McpTools().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpTools {
    return new McpTools().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpTools {
    return new McpTools().fromJsonString(jsonString, options);
  }

  static equals(a: McpTools | PlainMessage<McpTools> | undefined, b: McpTools | PlainMessage<McpTools> | undefined): boolean {
    return proto3.util.equals(McpTools, a, b);
  }
}

/**
 * @generated from message agent.v1.McpInstructions
 */
export class McpInstructions extends Message<McpInstructions> {
  /**
   * @generated from field: string server_name = 1;
   */
  serverName = "";

  /**
   * @generated from field: string instructions = 2;
   */
  instructions = "";

  constructor(data?: PartialMessage<McpInstructions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpInstructions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "instructions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpInstructions {
    return new McpInstructions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpInstructions {
    return new McpInstructions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpInstructions {
    return new McpInstructions().fromJsonString(jsonString, options);
  }

  static equals(a: McpInstructions | PlainMessage<McpInstructions> | undefined, b: McpInstructions | PlainMessage<McpInstructions> | undefined): boolean {
    return proto3.util.equals(McpInstructions, a, b);
  }
}

/**
 * @generated from message agent.v1.McpDescriptor
 */
export class McpDescriptor extends Message<McpDescriptor> {
  /**
   * @generated from field: string server_name = 1;
   */
  serverName = "";

  /**
   * @generated from field: string server_identifier = 2;
   */
  serverIdentifier = "";

  /**
   * @generated from field: optional string folder_path = 3;
   */
  folderPath?: string;

  /**
   * @generated from field: optional string server_use_instructions = 4;
   */
  serverUseInstructions?: string;

  /**
   * @generated from field: repeated agent.v1.McpToolDescriptor tools = 5;
   */
  tools: McpToolDescriptor[] = [];

  constructor(data?: PartialMessage<McpDescriptor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpDescriptor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "server_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "folder_path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "server_use_instructions", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "tools", kind: "message", T: McpToolDescriptor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpDescriptor {
    return new McpDescriptor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpDescriptor {
    return new McpDescriptor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpDescriptor {
    return new McpDescriptor().fromJsonString(jsonString, options);
  }

  static equals(a: McpDescriptor | PlainMessage<McpDescriptor> | undefined, b: McpDescriptor | PlainMessage<McpDescriptor> | undefined): boolean {
    return proto3.util.equals(McpDescriptor, a, b);
  }
}

/**
 * @generated from message agent.v1.McpToolDescriptor
 */
export class McpToolDescriptor extends Message<McpToolDescriptor> {
  /**
   * @generated from field: string tool_name = 1;
   */
  toolName = "";

  /**
   * @generated from field: optional string definition_path = 2;
   */
  definitionPath?: string;

  constructor(data?: PartialMessage<McpToolDescriptor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpToolDescriptor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tool_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "definition_path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpToolDescriptor {
    return new McpToolDescriptor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpToolDescriptor {
    return new McpToolDescriptor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpToolDescriptor {
    return new McpToolDescriptor().fromJsonString(jsonString, options);
  }

  static equals(a: McpToolDescriptor | PlainMessage<McpToolDescriptor> | undefined, b: McpToolDescriptor | PlainMessage<McpToolDescriptor> | undefined): boolean {
    return proto3.util.equals(McpToolDescriptor, a, b);
  }
}

/**
 * @generated from message agent.v1.McpFileSystemOptions
 */
export class McpFileSystemOptions extends Message<McpFileSystemOptions> {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled = false;

  /**
   * @generated from field: string workspace_project_dir = 2;
   */
  workspaceProjectDir = "";

  /**
   * @generated from field: repeated agent.v1.McpDescriptor mcp_descriptors = 3;
   */
  mcpDescriptors: McpDescriptor[] = [];

  constructor(data?: PartialMessage<McpFileSystemOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.McpFileSystemOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "workspace_project_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "mcp_descriptors", kind: "message", T: McpDescriptor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): McpFileSystemOptions {
    return new McpFileSystemOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): McpFileSystemOptions {
    return new McpFileSystemOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): McpFileSystemOptions {
    return new McpFileSystemOptions().fromJsonString(jsonString, options);
  }

  static equals(a: McpFileSystemOptions | PlainMessage<McpFileSystemOptions> | undefined, b: McpFileSystemOptions | PlainMessage<McpFileSystemOptions> | undefined): boolean {
    return proto3.util.equals(McpFileSystemOptions, a, b);
  }
}

