// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/record_screen_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum agent.v1.RecordingMode
 */
export enum RecordingMode {
  /**
   * @generated from enum value: RECORDING_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RECORDING_MODE_START_RECORDING = 1;
   */
  START_RECORDING = 1,

  /**
   * @generated from enum value: RECORDING_MODE_SAVE_RECORDING = 2;
   */
  SAVE_RECORDING = 2,

  /**
   * @generated from enum value: RECORDING_MODE_DISCARD_RECORDING = 3;
   */
  DISCARD_RECORDING = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RecordingMode)
proto3.util.setEnumType(RecordingMode, "agent.v1.RecordingMode", [
  { no: 0, name: "RECORDING_MODE_UNSPECIFIED" },
  { no: 1, name: "RECORDING_MODE_START_RECORDING" },
  { no: 2, name: "RECORDING_MODE_SAVE_RECORDING" },
  { no: 3, name: "RECORDING_MODE_DISCARD_RECORDING" },
]);

/**
 * @generated from enum agent.v1.RequestedFilePathRejectedReason
 */
export enum RequestedFilePathRejectedReason {
  /**
   * @generated from enum value: REQUESTED_FILE_PATH_REJECTED_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REQUESTED_FILE_PATH_REJECTED_REASON_SLASHES_NOT_ALLOWED = 1;
   */
  SLASHES_NOT_ALLOWED = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(RequestedFilePathRejectedReason)
proto3.util.setEnumType(RequestedFilePathRejectedReason, "agent.v1.RequestedFilePathRejectedReason", [
  { no: 0, name: "REQUESTED_FILE_PATH_REJECTED_REASON_UNSPECIFIED" },
  { no: 1, name: "REQUESTED_FILE_PATH_REJECTED_REASON_SLASHES_NOT_ALLOWED" },
]);

/**
 * @generated from message agent.v1.RecordScreenToolCall
 */
export class RecordScreenToolCall extends Message<RecordScreenToolCall> {
  /**
   * @generated from field: agent.v1.RecordScreenArgs args = 1;
   */
  args?: RecordScreenArgs;

  /**
   * @generated from field: agent.v1.RecordScreenResult result = 2;
   */
  result?: RecordScreenResult;

  constructor(data?: PartialMessage<RecordScreenToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: RecordScreenArgs },
    { no: 2, name: "result", kind: "message", T: RecordScreenResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenToolCall {
    return new RecordScreenToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenToolCall {
    return new RecordScreenToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenToolCall {
    return new RecordScreenToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenToolCall | PlainMessage<RecordScreenToolCall> | undefined, b: RecordScreenToolCall | PlainMessage<RecordScreenToolCall> | undefined): boolean {
    return proto3.util.equals(RecordScreenToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenArgs
 */
export class RecordScreenArgs extends Message<RecordScreenArgs> {
  /**
   * @generated from field: agent.v1.RecordingMode mode = 1;
   */
  mode = RecordingMode.UNSPECIFIED;

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  /**
   * @generated from field: optional string save_as_filename = 3;
   */
  saveAsFilename?: string;

  constructor(data?: PartialMessage<RecordScreenArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mode", kind: "enum", T: proto3.getEnumType(RecordingMode) },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "save_as_filename", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenArgs {
    return new RecordScreenArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenArgs {
    return new RecordScreenArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenArgs {
    return new RecordScreenArgs().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenArgs | PlainMessage<RecordScreenArgs> | undefined, b: RecordScreenArgs | PlainMessage<RecordScreenArgs> | undefined): boolean {
    return proto3.util.equals(RecordScreenArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenResult
 */
export class RecordScreenResult extends Message<RecordScreenResult> {
  /**
   * @generated from oneof agent.v1.RecordScreenResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.RecordScreenStartSuccess start_success = 1;
     */
    value: RecordScreenStartSuccess;
    case: "startSuccess";
  } | {
    /**
     * @generated from field: agent.v1.RecordScreenSaveSuccess save_success = 2;
     */
    value: RecordScreenSaveSuccess;
    case: "saveSuccess";
  } | {
    /**
     * @generated from field: agent.v1.RecordScreenDiscardSuccess discard_success = 3;
     */
    value: RecordScreenDiscardSuccess;
    case: "discardSuccess";
  } | {
    /**
     * @generated from field: agent.v1.RecordScreenFailure failure = 4;
     */
    value: RecordScreenFailure;
    case: "failure";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RecordScreenResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start_success", kind: "message", T: RecordScreenStartSuccess, oneof: "result" },
    { no: 2, name: "save_success", kind: "message", T: RecordScreenSaveSuccess, oneof: "result" },
    { no: 3, name: "discard_success", kind: "message", T: RecordScreenDiscardSuccess, oneof: "result" },
    { no: 4, name: "failure", kind: "message", T: RecordScreenFailure, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenResult {
    return new RecordScreenResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenResult {
    return new RecordScreenResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenResult {
    return new RecordScreenResult().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenResult | PlainMessage<RecordScreenResult> | undefined, b: RecordScreenResult | PlainMessage<RecordScreenResult> | undefined): boolean {
    return proto3.util.equals(RecordScreenResult, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenStartSuccess
 */
export class RecordScreenStartSuccess extends Message<RecordScreenStartSuccess> {
  /**
   * @generated from field: bool was_prior_recording_cancelled = 1;
   */
  wasPriorRecordingCancelled = false;

  /**
   * @generated from field: bool was_save_as_filename_ignored = 2;
   */
  wasSaveAsFilenameIgnored = false;

  constructor(data?: PartialMessage<RecordScreenStartSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenStartSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "was_prior_recording_cancelled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "was_save_as_filename_ignored", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenStartSuccess {
    return new RecordScreenStartSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenStartSuccess {
    return new RecordScreenStartSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenStartSuccess {
    return new RecordScreenStartSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenStartSuccess | PlainMessage<RecordScreenStartSuccess> | undefined, b: RecordScreenStartSuccess | PlainMessage<RecordScreenStartSuccess> | undefined): boolean {
    return proto3.util.equals(RecordScreenStartSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenSaveSuccess
 */
export class RecordScreenSaveSuccess extends Message<RecordScreenSaveSuccess> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: int64 recording_duration_ms = 2;
   */
  recordingDurationMs = protoInt64.zero;

  /**
   * @generated from field: optional agent.v1.RequestedFilePathRejectedReason requested_file_path_rejected_reason = 3;
   */
  requestedFilePathRejectedReason?: RequestedFilePathRejectedReason;

  constructor(data?: PartialMessage<RecordScreenSaveSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenSaveSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recording_duration_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "requested_file_path_rejected_reason", kind: "enum", T: proto3.getEnumType(RequestedFilePathRejectedReason), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenSaveSuccess {
    return new RecordScreenSaveSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenSaveSuccess {
    return new RecordScreenSaveSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenSaveSuccess {
    return new RecordScreenSaveSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenSaveSuccess | PlainMessage<RecordScreenSaveSuccess> | undefined, b: RecordScreenSaveSuccess | PlainMessage<RecordScreenSaveSuccess> | undefined): boolean {
    return proto3.util.equals(RecordScreenSaveSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenDiscardSuccess
 */
export class RecordScreenDiscardSuccess extends Message<RecordScreenDiscardSuccess> {
  constructor(data?: PartialMessage<RecordScreenDiscardSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenDiscardSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenDiscardSuccess {
    return new RecordScreenDiscardSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenDiscardSuccess {
    return new RecordScreenDiscardSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenDiscardSuccess {
    return new RecordScreenDiscardSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenDiscardSuccess | PlainMessage<RecordScreenDiscardSuccess> | undefined, b: RecordScreenDiscardSuccess | PlainMessage<RecordScreenDiscardSuccess> | undefined): boolean {
    return proto3.util.equals(RecordScreenDiscardSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.RecordScreenFailure
 */
export class RecordScreenFailure extends Message<RecordScreenFailure> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<RecordScreenFailure>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RecordScreenFailure";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecordScreenFailure {
    return new RecordScreenFailure().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecordScreenFailure {
    return new RecordScreenFailure().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecordScreenFailure {
    return new RecordScreenFailure().fromJsonString(jsonString, options);
  }

  static equals(a: RecordScreenFailure | PlainMessage<RecordScreenFailure> | undefined, b: RecordScreenFailure | PlainMessage<RecordScreenFailure> | undefined): boolean {
    return proto3.util.equals(RecordScreenFailure, a, b);
  }
}

