// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/reflect_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.ReflectArgs
 */
export class ReflectArgs extends Message<ReflectArgs> {
  /**
   * @generated from field: string unexpected_action_outcomes = 1;
   */
  unexpectedActionOutcomes = "";

  /**
   * @generated from field: string relevant_instructions = 2;
   */
  relevantInstructions = "";

  /**
   * @generated from field: string scenario_analysis = 3;
   */
  scenarioAnalysis = "";

  /**
   * @generated from field: string critical_synthesis = 4;
   */
  criticalSynthesis = "";

  /**
   * @generated from field: string next_steps = 5;
   */
  nextSteps = "";

  /**
   * @generated from field: string tool_call_id = 6;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<ReflectArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReflectArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "unexpected_action_outcomes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "relevant_instructions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "scenario_analysis", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "critical_synthesis", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "next_steps", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReflectArgs {
    return new ReflectArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReflectArgs {
    return new ReflectArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReflectArgs {
    return new ReflectArgs().fromJsonString(jsonString, options);
  }

  static equals(a: ReflectArgs | PlainMessage<ReflectArgs> | undefined, b: ReflectArgs | PlainMessage<ReflectArgs> | undefined): boolean {
    return proto3.util.equals(ReflectArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.ReflectResult
 */
export class ReflectResult extends Message<ReflectResult> {
  /**
   * @generated from oneof agent.v1.ReflectResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.ReflectSuccess success = 1;
     */
    value: ReflectSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.ReflectError error = 2;
     */
    value: ReflectError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ReflectResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReflectResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: ReflectSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: ReflectError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReflectResult {
    return new ReflectResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReflectResult {
    return new ReflectResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReflectResult {
    return new ReflectResult().fromJsonString(jsonString, options);
  }

  static equals(a: ReflectResult | PlainMessage<ReflectResult> | undefined, b: ReflectResult | PlainMessage<ReflectResult> | undefined): boolean {
    return proto3.util.equals(ReflectResult, a, b);
  }
}

/**
 * @generated from message agent.v1.ReflectSuccess
 */
export class ReflectSuccess extends Message<ReflectSuccess> {
  constructor(data?: PartialMessage<ReflectSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReflectSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReflectSuccess {
    return new ReflectSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReflectSuccess {
    return new ReflectSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReflectSuccess {
    return new ReflectSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: ReflectSuccess | PlainMessage<ReflectSuccess> | undefined, b: ReflectSuccess | PlainMessage<ReflectSuccess> | undefined): boolean {
    return proto3.util.equals(ReflectSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.ReflectError
 */
export class ReflectError extends Message<ReflectError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<ReflectError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReflectError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReflectError {
    return new ReflectError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReflectError {
    return new ReflectError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReflectError {
    return new ReflectError().fromJsonString(jsonString, options);
  }

  static equals(a: ReflectError | PlainMessage<ReflectError> | undefined, b: ReflectError | PlainMessage<ReflectError> | undefined): boolean {
    return proto3.util.equals(ReflectError, a, b);
  }
}

/**
 * @generated from message agent.v1.ReflectToolCall
 */
export class ReflectToolCall extends Message<ReflectToolCall> {
  /**
   * @generated from field: agent.v1.ReflectArgs args = 1;
   */
  args?: ReflectArgs;

  /**
   * @generated from field: agent.v1.ReflectResult result = 2;
   */
  result?: ReflectResult;

  constructor(data?: PartialMessage<ReflectToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.ReflectToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: ReflectArgs },
    { no: 2, name: "result", kind: "message", T: ReflectResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReflectToolCall {
    return new ReflectToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReflectToolCall {
    return new ReflectToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReflectToolCall {
    return new ReflectToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: ReflectToolCall | PlainMessage<ReflectToolCall> | undefined, b: ReflectToolCall | PlainMessage<ReflectToolCall> | undefined): boolean {
    return proto3.util.equals(ReflectToolCall, a, b);
  }
}

