// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/repo.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.RepositoryIndexingInfo
 */
export class RepositoryIndexingInfo extends Message<RepositoryIndexingInfo> {
  /**
   * @generated from field: string relative_workspace_path = 1;
   */
  relativeWorkspacePath = "";

  /**
   * @generated from field: repeated string remote_urls = 2;
   */
  remoteUrls: string[] = [];

  /**
   * @generated from field: repeated string remote_names = 3;
   */
  remoteNames: string[] = [];

  /**
   * @generated from field: string repo_name = 4;
   */
  repoName = "";

  /**
   * @generated from field: string repo_owner = 5;
   */
  repoOwner = "";

  /**
   * @generated from field: bool is_tracked = 6;
   */
  isTracked = false;

  /**
   * @generated from field: bool is_local = 7;
   */
  isLocal = false;

  /**
   * @generated from field: optional double orthogonal_transform_seed = 8;
   */
  orthogonalTransformSeed?: number;

  /**
   * @generated from field: string workspace_uri = 9;
   */
  workspaceUri = "";

  /**
   * @generated from field: string path_encryption_key = 10;
   */
  pathEncryptionKey = "";

  constructor(data?: PartialMessage<RepositoryIndexingInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RepositoryIndexingInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "relative_workspace_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "remote_urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "remote_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "repo_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "repo_owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "is_tracked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "is_local", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "orthogonal_transform_seed", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 9, name: "workspace_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "path_encryption_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RepositoryIndexingInfo {
    return new RepositoryIndexingInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RepositoryIndexingInfo {
    return new RepositoryIndexingInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RepositoryIndexingInfo {
    return new RepositoryIndexingInfo().fromJsonString(jsonString, options);
  }

  static equals(a: RepositoryIndexingInfo | PlainMessage<RepositoryIndexingInfo> | undefined, b: RepositoryIndexingInfo | PlainMessage<RepositoryIndexingInfo> | undefined): boolean {
    return proto3.util.equals(RepositoryIndexingInfo, a, b);
  }
}

/**
 * @generated from message agent.v1.GitRepoInfo
 */
export class GitRepoInfo extends Message<GitRepoInfo> {
  /**
   * @generated from field: string path = 1;
   */
  path = "";

  /**
   * @generated from field: string status = 2;
   */
  status = "";

  /**
   * @generated from field: string branch_name = 3;
   */
  branchName = "";

  /**
   * @generated from field: optional string remote_url = 4;
   */
  remoteUrl?: string;

  constructor(data?: PartialMessage<GitRepoInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.GitRepoInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "branch_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "remote_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GitRepoInfo {
    return new GitRepoInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GitRepoInfo {
    return new GitRepoInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GitRepoInfo {
    return new GitRepoInfo().fromJsonString(jsonString, options);
  }

  static equals(a: GitRepoInfo | PlainMessage<GitRepoInfo> | undefined, b: GitRepoInfo | PlainMessage<GitRepoInfo> | undefined): boolean {
    return proto3.util.equals(GitRepoInfo, a, b);
  }
}

