// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/request_context_exec.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { CursorRule } from "./cursor_rules_pb.js";
import { GitRepoInfo, RepositoryIndexingInfo } from "./repo_pb.js";
import { McpFileSystemOptions, McpInstructions, McpToolDefinition } from "./mcp_pb.js";
import { LsDirectoryTreeNode } from "./selected_context_pb.js";
import { SkillOptions } from "./cursor_packages_pb.js";
import { CustomSubagent } from "./subagents_pb.js";

/**
 * @generated from message agent.v1.RequestContextArgs
 */
export class RequestContextArgs extends Message<RequestContextArgs> {
  /**
   * @generated from field: optional string notes_session_id = 2;
   */
  notesSessionId?: string;

  /**
   * @generated from field: optional string workspace_id = 3;
   */
  workspaceId?: string;

  constructor(data?: PartialMessage<RequestContextArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "notes_session_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "workspace_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextArgs {
    return new RequestContextArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextArgs {
    return new RequestContextArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextArgs {
    return new RequestContextArgs().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextArgs | PlainMessage<RequestContextArgs> | undefined, b: RequestContextArgs | PlainMessage<RequestContextArgs> | undefined): boolean {
    return proto3.util.equals(RequestContextArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContextResult
 */
export class RequestContextResult extends Message<RequestContextResult> {
  /**
   * @generated from oneof agent.v1.RequestContextResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.RequestContextSuccess success = 1;
     */
    value: RequestContextSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.RequestContextError error = 2;
     */
    value: RequestContextError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.RequestContextRejected rejected = 3;
     */
    value: RequestContextRejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RequestContextResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: RequestContextSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: RequestContextError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: RequestContextRejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextResult {
    return new RequestContextResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextResult {
    return new RequestContextResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextResult {
    return new RequestContextResult().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextResult | PlainMessage<RequestContextResult> | undefined, b: RequestContextResult | PlainMessage<RequestContextResult> | undefined): boolean {
    return proto3.util.equals(RequestContextResult, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContextSuccess
 */
export class RequestContextSuccess extends Message<RequestContextSuccess> {
  /**
   * @generated from field: agent.v1.RequestContext request_context = 1;
   */
  requestContext?: RequestContext;

  constructor(data?: PartialMessage<RequestContextSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request_context", kind: "message", T: RequestContext },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextSuccess {
    return new RequestContextSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextSuccess {
    return new RequestContextSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextSuccess {
    return new RequestContextSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextSuccess | PlainMessage<RequestContextSuccess> | undefined, b: RequestContextSuccess | PlainMessage<RequestContextSuccess> | undefined): boolean {
    return proto3.util.equals(RequestContextSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContextError
 */
export class RequestContextError extends Message<RequestContextError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<RequestContextError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextError {
    return new RequestContextError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextError {
    return new RequestContextError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextError {
    return new RequestContextError().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextError | PlainMessage<RequestContextError> | undefined, b: RequestContextError | PlainMessage<RequestContextError> | undefined): boolean {
    return proto3.util.equals(RequestContextError, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContextRejected
 */
export class RequestContextRejected extends Message<RequestContextRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<RequestContextRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextRejected {
    return new RequestContextRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextRejected {
    return new RequestContextRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextRejected {
    return new RequestContextRejected().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextRejected | PlainMessage<RequestContextRejected> | undefined, b: RequestContextRejected | PlainMessage<RequestContextRejected> | undefined): boolean {
    return proto3.util.equals(RequestContextRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContextEnv
 */
export class RequestContextEnv extends Message<RequestContextEnv> {
  /**
   * @generated from field: string os_version = 1;
   */
  osVersion = "";

  /**
   * @generated from field: repeated string workspace_paths = 2;
   */
  workspacePaths: string[] = [];

  /**
   * @generated from field: string shell = 3;
   */
  shell = "";

  /**
   * @generated from field: bool sandbox_enabled = 5;
   */
  sandboxEnabled = false;

  /**
   * @generated from field: string terminals_folder = 7;
   */
  terminalsFolder = "";

  /**
   * @generated from field: string agent_shared_notes_folder = 8;
   */
  agentSharedNotesFolder = "";

  /**
   * @generated from field: string agent_conversation_notes_folder = 9;
   */
  agentConversationNotesFolder = "";

  /**
   * @generated from field: string time_zone = 10;
   */
  timeZone = "";

  /**
   * @generated from field: string project_folder = 11;
   */
  projectFolder = "";

  /**
   * @generated from field: string agent_transcripts_folder = 12;
   */
  agentTranscriptsFolder = "";

  /**
   * @generated from field: optional string artifacts_folder = 13;
   */
  artifactsFolder?: string;

  constructor(data?: PartialMessage<RequestContextEnv>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContextEnv";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "os_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "workspace_paths", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "shell", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sandbox_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "terminals_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "agent_shared_notes_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "agent_conversation_notes_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "time_zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "project_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "agent_transcripts_folder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "artifacts_folder", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContextEnv {
    return new RequestContextEnv().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContextEnv {
    return new RequestContextEnv().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContextEnv {
    return new RequestContextEnv().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContextEnv | PlainMessage<RequestContextEnv> | undefined, b: RequestContextEnv | PlainMessage<RequestContextEnv> | undefined): boolean {
    return proto3.util.equals(RequestContextEnv, a, b);
  }
}

/**
 * @generated from message agent.v1.DebugModeConfig
 */
export class DebugModeConfig extends Message<DebugModeConfig> {
  /**
   * @generated from field: string log_path = 1;
   */
  logPath = "";

  /**
   * @generated from field: string server_endpoint = 2;
   */
  serverEndpoint = "";

  constructor(data?: PartialMessage<DebugModeConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.DebugModeConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "log_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "server_endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DebugModeConfig {
    return new DebugModeConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DebugModeConfig {
    return new DebugModeConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DebugModeConfig {
    return new DebugModeConfig().fromJsonString(jsonString, options);
  }

  static equals(a: DebugModeConfig | PlainMessage<DebugModeConfig> | undefined, b: DebugModeConfig | PlainMessage<DebugModeConfig> | undefined): boolean {
    return proto3.util.equals(DebugModeConfig, a, b);
  }
}

/**
 * @generated from message agent.v1.RequestContext
 */
export class RequestContext extends Message<RequestContext> {
  /**
   * @generated from field: repeated agent.v1.CursorRule rules = 2;
   */
  rules: CursorRule[] = [];

  /**
   * @generated from field: agent.v1.RequestContextEnv env = 4;
   */
  env?: RequestContextEnv;

  /**
   * @generated from field: repeated agent.v1.RepositoryIndexingInfo repository_info = 6;
   */
  repositoryInfo: RepositoryIndexingInfo[] = [];

  /**
   * @generated from field: repeated agent.v1.McpToolDefinition tools = 7;
   */
  tools: McpToolDefinition[] = [];

  /**
   * @generated from field: optional string conversation_notes_listing = 8;
   */
  conversationNotesListing?: string;

  /**
   * @generated from field: optional string shared_notes_listing = 9;
   */
  sharedNotesListing?: string;

  /**
   * @generated from field: repeated agent.v1.GitRepoInfo git_repos = 11;
   */
  gitRepos: GitRepoInfo[] = [];

  /**
   * @generated from field: repeated agent.v1.LsDirectoryTreeNode project_layouts = 13;
   */
  projectLayouts: LsDirectoryTreeNode[] = [];

  /**
   * @generated from field: repeated agent.v1.McpInstructions mcp_instructions = 14;
   */
  mcpInstructions: McpInstructions[] = [];

  /**
   * @generated from field: optional agent.v1.DebugModeConfig debug_mode_config = 15;
   */
  debugModeConfig?: DebugModeConfig;

  /**
   * @generated from field: optional string cloud_rule = 16;
   */
  cloudRule?: string;

  /**
   * @generated from field: optional bool web_search_enabled = 17;
   */
  webSearchEnabled?: boolean;

  /**
   * @generated from field: optional agent.v1.SkillOptions skill_options = 18;
   */
  skillOptions?: SkillOptions;

  /**
   * @generated from field: optional bool repository_info_should_query_prod = 19;
   */
  repositoryInfoShouldQueryProd?: boolean;

  /**
   * @generated from field: map<string, string> file_contents = 20;
   */
  fileContents: { [key: string]: string } = {};

  /**
   * @generated from field: optional string user_intent_summary = 21;
   */
  userIntentSummary?: string;

  /**
   * @generated from field: repeated agent.v1.CustomSubagent custom_subagents = 22;
   */
  customSubagents: CustomSubagent[] = [];

  /**
   * @generated from field: optional agent.v1.McpFileSystemOptions mcp_file_system_options = 23;
   */
  mcpFileSystemOptions?: McpFileSystemOptions;

  /**
   * @generated from field: optional bool web_fetch_enabled = 24;
   */
  webFetchEnabled?: boolean;

  /**
   * @generated from field: optional string hooks_additional_context = 25;
   */
  hooksAdditionalContext?: string;

  /**
   * @generated from field: optional string commit_attribution_message = 26;
   */
  commitAttributionMessage?: string;

  /**
   * @generated from field: optional string pr_attribution_message = 27;
   */
  prAttributionMessage?: string;

  constructor(data?: PartialMessage<RequestContext>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.RequestContext";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "rules", kind: "message", T: CursorRule, repeated: true },
    { no: 4, name: "env", kind: "message", T: RequestContextEnv },
    { no: 6, name: "repository_info", kind: "message", T: RepositoryIndexingInfo, repeated: true },
    { no: 7, name: "tools", kind: "message", T: McpToolDefinition, repeated: true },
    { no: 8, name: "conversation_notes_listing", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "shared_notes_listing", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "git_repos", kind: "message", T: GitRepoInfo, repeated: true },
    { no: 13, name: "project_layouts", kind: "message", T: LsDirectoryTreeNode, repeated: true },
    { no: 14, name: "mcp_instructions", kind: "message", T: McpInstructions, repeated: true },
    { no: 15, name: "debug_mode_config", kind: "message", T: DebugModeConfig, opt: true },
    { no: 16, name: "cloud_rule", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 17, name: "web_search_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 18, name: "skill_options", kind: "message", T: SkillOptions, opt: true },
    { no: 19, name: "repository_info_should_query_prod", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 20, name: "file_contents", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 21, name: "user_intent_summary", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 22, name: "custom_subagents", kind: "message", T: CustomSubagent, repeated: true },
    { no: 23, name: "mcp_file_system_options", kind: "message", T: McpFileSystemOptions, opt: true },
    { no: 24, name: "web_fetch_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 25, name: "hooks_additional_context", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 26, name: "commit_attribution_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 27, name: "pr_attribution_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestContext {
    return new RequestContext().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestContext {
    return new RequestContext().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestContext {
    return new RequestContext().fromJsonString(jsonString, options);
  }

  static equals(a: RequestContext | PlainMessage<RequestContext> | undefined, b: RequestContext | PlainMessage<RequestContext> | undefined): boolean {
    return proto3.util.equals(RequestContext, a, b);
  }
}

