// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/semsearch_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.SemSearchToolCall
 */
export class SemSearchToolCall extends Message<SemSearchToolCall> {
  /**
   * @generated from field: agent.v1.SemSearchToolArgs args = 1;
   */
  args?: SemSearchToolArgs;

  /**
   * @generated from field: agent.v1.SemSearchToolResult result = 2;
   */
  result?: SemSearchToolResult;

  constructor(data?: PartialMessage<SemSearchToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SemSearchToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: SemSearchToolArgs },
    { no: 2, name: "result", kind: "message", T: SemSearchToolResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SemSearchToolCall {
    return new SemSearchToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SemSearchToolCall {
    return new SemSearchToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SemSearchToolCall {
    return new SemSearchToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: SemSearchToolCall | PlainMessage<SemSearchToolCall> | undefined, b: SemSearchToolCall | PlainMessage<SemSearchToolCall> | undefined): boolean {
    return proto3.util.equals(SemSearchToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.SemSearchToolArgs
 */
export class SemSearchToolArgs extends Message<SemSearchToolArgs> {
  /**
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * @generated from field: repeated string target_directories = 2;
   */
  targetDirectories: string[] = [];

  /**
   * @generated from field: string explanation = 3;
   */
  explanation = "";

  constructor(data?: PartialMessage<SemSearchToolArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SemSearchToolArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "target_directories", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SemSearchToolArgs {
    return new SemSearchToolArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SemSearchToolArgs {
    return new SemSearchToolArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SemSearchToolArgs {
    return new SemSearchToolArgs().fromJsonString(jsonString, options);
  }

  static equals(a: SemSearchToolArgs | PlainMessage<SemSearchToolArgs> | undefined, b: SemSearchToolArgs | PlainMessage<SemSearchToolArgs> | undefined): boolean {
    return proto3.util.equals(SemSearchToolArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.SemSearchToolResult
 */
export class SemSearchToolResult extends Message<SemSearchToolResult> {
  /**
   * @generated from oneof agent.v1.SemSearchToolResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.SemSearchToolSuccess success = 1;
     */
    value: SemSearchToolSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.SemSearchToolError error = 2;
     */
    value: SemSearchToolError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<SemSearchToolResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SemSearchToolResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: SemSearchToolSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: SemSearchToolError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SemSearchToolResult {
    return new SemSearchToolResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SemSearchToolResult {
    return new SemSearchToolResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SemSearchToolResult {
    return new SemSearchToolResult().fromJsonString(jsonString, options);
  }

  static equals(a: SemSearchToolResult | PlainMessage<SemSearchToolResult> | undefined, b: SemSearchToolResult | PlainMessage<SemSearchToolResult> | undefined): boolean {
    return proto3.util.equals(SemSearchToolResult, a, b);
  }
}

/**
 * @generated from message agent.v1.SemSearchToolSuccess
 */
export class SemSearchToolSuccess extends Message<SemSearchToolSuccess> {
  /**
   * @generated from field: string results = 1;
   */
  results = "";

  /**
   * @generated from field: repeated bytes code_results = 2;
   */
  codeResults: Uint8Array[] = [];

  constructor(data?: PartialMessage<SemSearchToolSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SemSearchToolSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "results", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code_results", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SemSearchToolSuccess {
    return new SemSearchToolSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SemSearchToolSuccess {
    return new SemSearchToolSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SemSearchToolSuccess {
    return new SemSearchToolSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: SemSearchToolSuccess | PlainMessage<SemSearchToolSuccess> | undefined, b: SemSearchToolSuccess | PlainMessage<SemSearchToolSuccess> | undefined): boolean {
    return proto3.util.equals(SemSearchToolSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.SemSearchToolError
 */
export class SemSearchToolError extends Message<SemSearchToolError> {
  /**
   * @generated from field: string error_message = 1;
   */
  errorMessage = "";

  constructor(data?: PartialMessage<SemSearchToolError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SemSearchToolError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SemSearchToolError {
    return new SemSearchToolError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SemSearchToolError {
    return new SemSearchToolError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SemSearchToolError {
    return new SemSearchToolError().fromJsonString(jsonString, options);
  }

  static equals(a: SemSearchToolError | PlainMessage<SemSearchToolError> | undefined, b: SemSearchToolError | PlainMessage<SemSearchToolError> | undefined): boolean {
    return proto3.util.equals(SemSearchToolError, a, b);
  }
}

