// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/start_grind_execution_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.StartGrindExecutionArgs
 */
export class StartGrindExecutionArgs extends Message<StartGrindExecutionArgs> {
  /**
   * @generated from field: optional string explanation = 1;
   */
  explanation?: string;

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<StartGrindExecutionArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StartGrindExecutionArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGrindExecutionArgs {
    return new StartGrindExecutionArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGrindExecutionArgs {
    return new StartGrindExecutionArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGrindExecutionArgs {
    return new StartGrindExecutionArgs().fromJsonString(jsonString, options);
  }

  static equals(a: StartGrindExecutionArgs | PlainMessage<StartGrindExecutionArgs> | undefined, b: StartGrindExecutionArgs | PlainMessage<StartGrindExecutionArgs> | undefined): boolean {
    return proto3.util.equals(StartGrindExecutionArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.StartGrindExecutionResult
 */
export class StartGrindExecutionResult extends Message<StartGrindExecutionResult> {
  /**
   * @generated from oneof agent.v1.StartGrindExecutionResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.StartGrindExecutionSuccess success = 1;
     */
    value: StartGrindExecutionSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.StartGrindExecutionError error = 2;
     */
    value: StartGrindExecutionError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<StartGrindExecutionResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StartGrindExecutionResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: StartGrindExecutionSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: StartGrindExecutionError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGrindExecutionResult {
    return new StartGrindExecutionResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGrindExecutionResult {
    return new StartGrindExecutionResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGrindExecutionResult {
    return new StartGrindExecutionResult().fromJsonString(jsonString, options);
  }

  static equals(a: StartGrindExecutionResult | PlainMessage<StartGrindExecutionResult> | undefined, b: StartGrindExecutionResult | PlainMessage<StartGrindExecutionResult> | undefined): boolean {
    return proto3.util.equals(StartGrindExecutionResult, a, b);
  }
}

/**
 * @generated from message agent.v1.StartGrindExecutionSuccess
 */
export class StartGrindExecutionSuccess extends Message<StartGrindExecutionSuccess> {
  constructor(data?: PartialMessage<StartGrindExecutionSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StartGrindExecutionSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGrindExecutionSuccess {
    return new StartGrindExecutionSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGrindExecutionSuccess {
    return new StartGrindExecutionSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGrindExecutionSuccess {
    return new StartGrindExecutionSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: StartGrindExecutionSuccess | PlainMessage<StartGrindExecutionSuccess> | undefined, b: StartGrindExecutionSuccess | PlainMessage<StartGrindExecutionSuccess> | undefined): boolean {
    return proto3.util.equals(StartGrindExecutionSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.StartGrindExecutionError
 */
export class StartGrindExecutionError extends Message<StartGrindExecutionError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<StartGrindExecutionError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StartGrindExecutionError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGrindExecutionError {
    return new StartGrindExecutionError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGrindExecutionError {
    return new StartGrindExecutionError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGrindExecutionError {
    return new StartGrindExecutionError().fromJsonString(jsonString, options);
  }

  static equals(a: StartGrindExecutionError | PlainMessage<StartGrindExecutionError> | undefined, b: StartGrindExecutionError | PlainMessage<StartGrindExecutionError> | undefined): boolean {
    return proto3.util.equals(StartGrindExecutionError, a, b);
  }
}

/**
 * @generated from message agent.v1.StartGrindExecutionToolCall
 */
export class StartGrindExecutionToolCall extends Message<StartGrindExecutionToolCall> {
  /**
   * @generated from field: agent.v1.StartGrindExecutionArgs args = 1;
   */
  args?: StartGrindExecutionArgs;

  /**
   * @generated from field: agent.v1.StartGrindExecutionResult result = 2;
   */
  result?: StartGrindExecutionResult;

  constructor(data?: PartialMessage<StartGrindExecutionToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.StartGrindExecutionToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: StartGrindExecutionArgs },
    { no: 2, name: "result", kind: "message", T: StartGrindExecutionResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartGrindExecutionToolCall {
    return new StartGrindExecutionToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartGrindExecutionToolCall {
    return new StartGrindExecutionToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartGrindExecutionToolCall {
    return new StartGrindExecutionToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: StartGrindExecutionToolCall | PlainMessage<StartGrindExecutionToolCall> | undefined, b: StartGrindExecutionToolCall | PlainMessage<StartGrindExecutionToolCall> | undefined): boolean {
    return proto3.util.equals(StartGrindExecutionToolCall, a, b);
  }
}

