// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/subagents.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum agent.v1.CustomSubagentPermissionMode
 */
export enum CustomSubagentPermissionMode {
  /**
   * @generated from enum value: CUSTOM_SUBAGENT_PERMISSION_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CUSTOM_SUBAGENT_PERMISSION_MODE_DEFAULT = 1;
   */
  DEFAULT = 1,

  /**
   * @generated from enum value: CUSTOM_SUBAGENT_PERMISSION_MODE_READONLY = 2;
   */
  READONLY = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(CustomSubagentPermissionMode)
proto3.util.setEnumType(CustomSubagentPermissionMode, "agent.v1.CustomSubagentPermissionMode", [
  { no: 0, name: "CUSTOM_SUBAGENT_PERMISSION_MODE_UNSPECIFIED" },
  { no: 1, name: "CUSTOM_SUBAGENT_PERMISSION_MODE_DEFAULT" },
  { no: 2, name: "CUSTOM_SUBAGENT_PERMISSION_MODE_READONLY" },
]);

/**
 * @generated from message agent.v1.TaskArgs
 */
export class TaskArgs extends Message<TaskArgs> {
  /**
   * @generated from field: string description = 1;
   */
  description = "";

  /**
   * @generated from field: string prompt = 2;
   */
  prompt = "";

  /**
   * @generated from field: agent.v1.SubagentType subagent_type = 3;
   */
  subagentType?: SubagentType;

  /**
   * @generated from field: optional string model = 4;
   */
  model?: string;

  /**
   * @generated from field: optional string resume = 5;
   */
  resume?: string;

  constructor(data?: PartialMessage<TaskArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subagent_type", kind: "message", T: SubagentType },
    { no: 4, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "resume", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskArgs {
    return new TaskArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskArgs {
    return new TaskArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskArgs {
    return new TaskArgs().fromJsonString(jsonString, options);
  }

  static equals(a: TaskArgs | PlainMessage<TaskArgs> | undefined, b: TaskArgs | PlainMessage<TaskArgs> | undefined): boolean {
    return proto3.util.equals(TaskArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.TaskSuccess
 */
export class TaskSuccess extends Message<TaskSuccess> {
  /**
   * ConversationStep serialized
   *
   * @generated from field: repeated bytes conversation_steps = 1;
   */
  conversationSteps: Uint8Array[] = [];

  /**
   * @generated from field: optional string agent_id = 2;
   */
  agentId?: string;

  /**
   * @generated from field: bool is_background = 3;
   */
  isBackground = false;

  /**
   * @generated from field: optional uint64 duration_ms = 4;
   */
  durationMs?: bigint;

  constructor(data?: PartialMessage<TaskSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_steps", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
    { no: 2, name: "agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "is_background", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "duration_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskSuccess {
    return new TaskSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskSuccess {
    return new TaskSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskSuccess {
    return new TaskSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: TaskSuccess | PlainMessage<TaskSuccess> | undefined, b: TaskSuccess | PlainMessage<TaskSuccess> | undefined): boolean {
    return proto3.util.equals(TaskSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.TaskError
 */
export class TaskError extends Message<TaskError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<TaskError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskError {
    return new TaskError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskError {
    return new TaskError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskError {
    return new TaskError().fromJsonString(jsonString, options);
  }

  static equals(a: TaskError | PlainMessage<TaskError> | undefined, b: TaskError | PlainMessage<TaskError> | undefined): boolean {
    return proto3.util.equals(TaskError, a, b);
  }
}

/**
 * @generated from message agent.v1.TaskResult
 */
export class TaskResult extends Message<TaskResult> {
  /**
   * @generated from oneof agent.v1.TaskResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.TaskSuccess success = 1;
     */
    value: TaskSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.TaskError error = 2;
     */
    value: TaskError;
    case: "error";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<TaskResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: TaskSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: TaskError, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskResult {
    return new TaskResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskResult {
    return new TaskResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskResult {
    return new TaskResult().fromJsonString(jsonString, options);
  }

  static equals(a: TaskResult | PlainMessage<TaskResult> | undefined, b: TaskResult | PlainMessage<TaskResult> | undefined): boolean {
    return proto3.util.equals(TaskResult, a, b);
  }
}

/**
 * @generated from message agent.v1.TaskToolCall
 */
export class TaskToolCall extends Message<TaskToolCall> {
  /**
   * @generated from field: agent.v1.TaskArgs args = 1;
   */
  args?: TaskArgs;

  /**
   * @generated from field: agent.v1.TaskResult result = 2;
   */
  result?: TaskResult;

  constructor(data?: PartialMessage<TaskToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: TaskArgs },
    { no: 2, name: "result", kind: "message", T: TaskResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskToolCall {
    return new TaskToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskToolCall {
    return new TaskToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskToolCall {
    return new TaskToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: TaskToolCall | PlainMessage<TaskToolCall> | undefined, b: TaskToolCall | PlainMessage<TaskToolCall> | undefined): boolean {
    return proto3.util.equals(TaskToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.TaskToolCallDelta
 */
export class TaskToolCallDelta extends Message<TaskToolCallDelta> {
  /**
   * InteractionUpdate serialized
   *
   * @generated from field: bytes interaction_update = 1;
   */
  interactionUpdate = new Uint8Array(0);

  constructor(data?: PartialMessage<TaskToolCallDelta>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.TaskToolCallDelta";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "interaction_update", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaskToolCallDelta {
    return new TaskToolCallDelta().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaskToolCallDelta {
    return new TaskToolCallDelta().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaskToolCallDelta {
    return new TaskToolCallDelta().fromJsonString(jsonString, options);
  }

  static equals(a: TaskToolCallDelta | PlainMessage<TaskToolCallDelta> | undefined, b: TaskToolCallDelta | PlainMessage<TaskToolCallDelta> | undefined): boolean {
    return proto3.util.equals(TaskToolCallDelta, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentType
 */
export class SubagentType extends Message<SubagentType> {
  /**
   * @generated from oneof agent.v1.SubagentType.type
   */
  type: {
    /**
     * @generated from field: agent.v1.SubagentTypeUnspecified unspecified = 1;
     */
    value: SubagentTypeUnspecified;
    case: "unspecified";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeComputerUse computer_use = 2;
     */
    value: SubagentTypeComputerUse;
    case: "computerUse";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeCustom custom = 3;
     */
    value: SubagentTypeCustom;
    case: "custom";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeExplore explore = 4;
     */
    value: SubagentTypeExplore;
    case: "explore";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeMediaReview media_review = 5;
     */
    value: SubagentTypeMediaReview;
    case: "mediaReview";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeBash bash = 6;
     */
    value: SubagentTypeBash;
    case: "bash";
  } | {
    /**
     * @generated from field: agent.v1.SubagentTypeBrowserUse browser_use = 7;
     */
    value: SubagentTypeBrowserUse;
    case: "browserUse";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<SubagentType>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentType";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "unspecified", kind: "message", T: SubagentTypeUnspecified, oneof: "type" },
    { no: 2, name: "computer_use", kind: "message", T: SubagentTypeComputerUse, oneof: "type" },
    { no: 3, name: "custom", kind: "message", T: SubagentTypeCustom, oneof: "type" },
    { no: 4, name: "explore", kind: "message", T: SubagentTypeExplore, oneof: "type" },
    { no: 5, name: "media_review", kind: "message", T: SubagentTypeMediaReview, oneof: "type" },
    { no: 6, name: "bash", kind: "message", T: SubagentTypeBash, oneof: "type" },
    { no: 7, name: "browser_use", kind: "message", T: SubagentTypeBrowserUse, oneof: "type" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentType {
    return new SubagentType().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentType {
    return new SubagentType().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentType {
    return new SubagentType().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentType | PlainMessage<SubagentType> | undefined, b: SubagentType | PlainMessage<SubagentType> | undefined): boolean {
    return proto3.util.equals(SubagentType, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeUnspecified
 */
export class SubagentTypeUnspecified extends Message<SubagentTypeUnspecified> {
  constructor(data?: PartialMessage<SubagentTypeUnspecified>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeUnspecified";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeUnspecified {
    return new SubagentTypeUnspecified().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeUnspecified {
    return new SubagentTypeUnspecified().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeUnspecified {
    return new SubagentTypeUnspecified().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeUnspecified | PlainMessage<SubagentTypeUnspecified> | undefined, b: SubagentTypeUnspecified | PlainMessage<SubagentTypeUnspecified> | undefined): boolean {
    return proto3.util.equals(SubagentTypeUnspecified, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeComputerUse
 */
export class SubagentTypeComputerUse extends Message<SubagentTypeComputerUse> {
  constructor(data?: PartialMessage<SubagentTypeComputerUse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeComputerUse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeComputerUse {
    return new SubagentTypeComputerUse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeComputerUse {
    return new SubagentTypeComputerUse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeComputerUse {
    return new SubagentTypeComputerUse().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeComputerUse | PlainMessage<SubagentTypeComputerUse> | undefined, b: SubagentTypeComputerUse | PlainMessage<SubagentTypeComputerUse> | undefined): boolean {
    return proto3.util.equals(SubagentTypeComputerUse, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeExplore
 */
export class SubagentTypeExplore extends Message<SubagentTypeExplore> {
  constructor(data?: PartialMessage<SubagentTypeExplore>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeExplore";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeExplore {
    return new SubagentTypeExplore().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeExplore {
    return new SubagentTypeExplore().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeExplore {
    return new SubagentTypeExplore().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeExplore | PlainMessage<SubagentTypeExplore> | undefined, b: SubagentTypeExplore | PlainMessage<SubagentTypeExplore> | undefined): boolean {
    return proto3.util.equals(SubagentTypeExplore, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeCustom
 */
export class SubagentTypeCustom extends Message<SubagentTypeCustom> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  constructor(data?: PartialMessage<SubagentTypeCustom>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeCustom";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeCustom {
    return new SubagentTypeCustom().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeCustom {
    return new SubagentTypeCustom().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeCustom {
    return new SubagentTypeCustom().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeCustom | PlainMessage<SubagentTypeCustom> | undefined, b: SubagentTypeCustom | PlainMessage<SubagentTypeCustom> | undefined): boolean {
    return proto3.util.equals(SubagentTypeCustom, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeBash
 */
export class SubagentTypeBash extends Message<SubagentTypeBash> {
  constructor(data?: PartialMessage<SubagentTypeBash>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeBash";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeBash {
    return new SubagentTypeBash().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeBash {
    return new SubagentTypeBash().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeBash {
    return new SubagentTypeBash().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeBash | PlainMessage<SubagentTypeBash> | undefined, b: SubagentTypeBash | PlainMessage<SubagentTypeBash> | undefined): boolean {
    return proto3.util.equals(SubagentTypeBash, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeBrowserUse
 */
export class SubagentTypeBrowserUse extends Message<SubagentTypeBrowserUse> {
  constructor(data?: PartialMessage<SubagentTypeBrowserUse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeBrowserUse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeBrowserUse {
    return new SubagentTypeBrowserUse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeBrowserUse {
    return new SubagentTypeBrowserUse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeBrowserUse {
    return new SubagentTypeBrowserUse().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeBrowserUse | PlainMessage<SubagentTypeBrowserUse> | undefined, b: SubagentTypeBrowserUse | PlainMessage<SubagentTypeBrowserUse> | undefined): boolean {
    return proto3.util.equals(SubagentTypeBrowserUse, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentTypeMediaReview
 */
export class SubagentTypeMediaReview extends Message<SubagentTypeMediaReview> {
  constructor(data?: PartialMessage<SubagentTypeMediaReview>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentTypeMediaReview";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentTypeMediaReview {
    return new SubagentTypeMediaReview().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentTypeMediaReview {
    return new SubagentTypeMediaReview().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentTypeMediaReview {
    return new SubagentTypeMediaReview().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentTypeMediaReview | PlainMessage<SubagentTypeMediaReview> | undefined, b: SubagentTypeMediaReview | PlainMessage<SubagentTypeMediaReview> | undefined): boolean {
    return proto3.util.equals(SubagentTypeMediaReview, a, b);
  }
}

/**
 * @generated from message agent.v1.CustomSubagent
 */
export class CustomSubagent extends Message<CustomSubagent> {
  /**
   * @generated from field: string full_path = 1;
   */
  fullPath = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: repeated string tools = 4;
   */
  tools: string[] = [];

  /**
   * @generated from field: string model = 5;
   */
  model = "";

  /**
   * @generated from field: string prompt = 6;
   */
  prompt = "";

  /**
   * @generated from field: agent.v1.CustomSubagentPermissionMode permission_mode = 7;
   */
  permissionMode = CustomSubagentPermissionMode.UNSPECIFIED;

  constructor(data?: PartialMessage<CustomSubagent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CustomSubagent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "full_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tools", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "permission_mode", kind: "enum", T: proto3.getEnumType(CustomSubagentPermissionMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CustomSubagent {
    return new CustomSubagent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CustomSubagent {
    return new CustomSubagent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CustomSubagent {
    return new CustomSubagent().fromJsonString(jsonString, options);
  }

  static equals(a: CustomSubagent | PlainMessage<CustomSubagent> | undefined, b: CustomSubagent | PlainMessage<CustomSubagent> | undefined): boolean {
    return proto3.util.equals(CustomSubagent, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentPersistedState
 */
export class SubagentPersistedState extends Message<SubagentPersistedState> {
  /**
   * ConversationStateStructure serialized
   *
   * @generated from field: bytes conversation_state = 1;
   */
  conversationState = new Uint8Array(0);

  /**
   * @generated from field: uint64 created_timestamp_ms = 2;
   */
  createdTimestampMs = protoInt64.zero;

  /**
   * @generated from field: uint64 last_used_timestamp_ms = 3;
   */
  lastUsedTimestampMs = protoInt64.zero;

  /**
   * @generated from field: agent.v1.SubagentType subagent_type = 4;
   */
  subagentType?: SubagentType;

  constructor(data?: PartialMessage<SubagentPersistedState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentPersistedState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_state", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "created_timestamp_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "last_used_timestamp_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "subagent_type", kind: "message", T: SubagentType },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentPersistedState {
    return new SubagentPersistedState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentPersistedState {
    return new SubagentPersistedState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentPersistedState {
    return new SubagentPersistedState().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentPersistedState | PlainMessage<SubagentPersistedState> | undefined, b: SubagentPersistedState | PlainMessage<SubagentPersistedState> | undefined): boolean {
    return proto3.util.equals(SubagentPersistedState, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentStartRequestQuery
 */
export class SubagentStartRequestQuery extends Message<SubagentStartRequestQuery> {
  /**
   * @generated from field: string subagent_id = 1;
   */
  subagentId = "";

  /**
   * @generated from field: string subagent_type = 2;
   */
  subagentType = "";

  /**
   * @generated from field: string task = 3;
   */
  task = "";

  /**
   * @generated from field: string parent_conversation_id = 4;
   */
  parentConversationId = "";

  /**
   * @generated from field: optional string tool_call_id = 5;
   */
  toolCallId?: string;

  /**
   * @generated from field: optional string subagent_model = 6;
   */
  subagentModel?: string;

  /**
   * @generated from field: bool is_parallel_worker = 7;
   */
  isParallelWorker = false;

  /**
   * @generated from field: optional string git_branch = 8;
   */
  gitBranch?: string;

  /**
   * @generated from field: optional string conversation_id = 9;
   */
  conversationId?: string;

  /**
   * @generated from field: optional string generation_id = 10;
   */
  generationId?: string;

  /**
   * @generated from field: optional string model = 11;
   */
  model?: string;

  constructor(data?: PartialMessage<SubagentStartRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentStartRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subagent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subagent_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "task", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "parent_conversation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "subagent_model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "is_parallel_worker", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "git_branch", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "conversation_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "generation_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentStartRequestQuery {
    return new SubagentStartRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentStartRequestQuery {
    return new SubagentStartRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentStartRequestQuery {
    return new SubagentStartRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentStartRequestQuery | PlainMessage<SubagentStartRequestQuery> | undefined, b: SubagentStartRequestQuery | PlainMessage<SubagentStartRequestQuery> | undefined): boolean {
    return proto3.util.equals(SubagentStartRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentStartRequestResponse
 */
export class SubagentStartRequestResponse extends Message<SubagentStartRequestResponse> {
  /**
   * @generated from field: optional string permission = 1;
   */
  permission?: string;

  /**
   * @generated from field: optional string user_message = 2;
   */
  userMessage?: string;

  constructor(data?: PartialMessage<SubagentStartRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentStartRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "permission", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "user_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentStartRequestResponse {
    return new SubagentStartRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentStartRequestResponse {
    return new SubagentStartRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentStartRequestResponse {
    return new SubagentStartRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentStartRequestResponse | PlainMessage<SubagentStartRequestResponse> | undefined, b: SubagentStartRequestResponse | PlainMessage<SubagentStartRequestResponse> | undefined): boolean {
    return proto3.util.equals(SubagentStartRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentStopRequestQuery
 */
export class SubagentStopRequestQuery extends Message<SubagentStopRequestQuery> {
  /**
   * @generated from field: string subagent_id = 1;
   */
  subagentId = "";

  /**
   * @generated from field: string subagent_type = 2;
   */
  subagentType = "";

  /**
   * @generated from field: string status = 3;
   */
  status = "";

  /**
   * @generated from field: int64 duration_ms = 4;
   */
  durationMs = protoInt64.zero;

  /**
   * @generated from field: optional string summary = 5;
   */
  summary?: string;

  /**
   * @generated from field: string parent_conversation_id = 6;
   */
  parentConversationId = "";

  /**
   * @generated from field: int32 message_count = 7;
   */
  messageCount = 0;

  /**
   * @generated from field: int32 tool_call_count = 8;
   */
  toolCallCount = 0;

  /**
   * @generated from field: optional string error_message = 9;
   */
  errorMessage?: string;

  /**
   * @generated from field: repeated string modified_files = 10;
   */
  modifiedFiles: string[] = [];

  /**
   * @generated from field: optional string git_branch = 11;
   */
  gitBranch?: string;

  /**
   * @generated from field: optional string conversation_id = 12;
   */
  conversationId?: string;

  /**
   * @generated from field: optional string generation_id = 13;
   */
  generationId?: string;

  /**
   * @generated from field: optional string model = 14;
   */
  model?: string;

  /**
   * @generated from field: int32 loop_count = 15;
   */
  loopCount = 0;

  /**
   * @generated from field: optional string task = 16;
   */
  task?: string;

  /**
   * @generated from field: optional string description = 17;
   */
  description?: string;

  constructor(data?: PartialMessage<SubagentStopRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentStopRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subagent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subagent_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "duration_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "summary", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "parent_conversation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "message_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "tool_call_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "modified_files", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 11, name: "git_branch", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 12, name: "conversation_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "generation_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 14, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 15, name: "loop_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 16, name: "task", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 17, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentStopRequestQuery {
    return new SubagentStopRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentStopRequestQuery {
    return new SubagentStopRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentStopRequestQuery {
    return new SubagentStopRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentStopRequestQuery | PlainMessage<SubagentStopRequestQuery> | undefined, b: SubagentStopRequestQuery | PlainMessage<SubagentStopRequestQuery> | undefined): boolean {
    return proto3.util.equals(SubagentStopRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.SubagentStopRequestResponse
 */
export class SubagentStopRequestResponse extends Message<SubagentStopRequestResponse> {
  /**
   * @generated from field: optional string followup_message = 1;
   */
  followupMessage?: string;

  constructor(data?: PartialMessage<SubagentStopRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SubagentStopRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "followup_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubagentStopRequestResponse {
    return new SubagentStopRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubagentStopRequestResponse {
    return new SubagentStopRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubagentStopRequestResponse {
    return new SubagentStopRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubagentStopRequestResponse | PlainMessage<SubagentStopRequestResponse> | undefined, b: SubagentStopRequestResponse | PlainMessage<SubagentStopRequestResponse> | undefined): boolean {
    return proto3.util.equals(SubagentStopRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.CancelSubagentAction
 */
export class CancelSubagentAction extends Message<CancelSubagentAction> {
  /**
   * @generated from field: string subagent_id = 1;
   */
  subagentId = "";

  constructor(data?: PartialMessage<CancelSubagentAction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.CancelSubagentAction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subagent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelSubagentAction {
    return new CancelSubagentAction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelSubagentAction {
    return new CancelSubagentAction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelSubagentAction {
    return new CancelSubagentAction().fromJsonString(jsonString, options);
  }

  static equals(a: CancelSubagentAction | PlainMessage<CancelSubagentAction> | undefined, b: CancelSubagentAction | PlainMessage<CancelSubagentAction> | undefined): boolean {
    return proto3.util.equals(CancelSubagentAction, a, b);
  }
}

