// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/switch_mode_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.SwitchModeArgs
 */
export class SwitchModeArgs extends Message<SwitchModeArgs> {
  /**
   * @generated from field: string target_mode_id = 1;
   */
  targetModeId = "";

  /**
   * @generated from field: optional string explanation = 2;
   */
  explanation?: string;

  /**
   * @generated from field: string tool_call_id = 3;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<SwitchModeArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_mode_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeArgs {
    return new SwitchModeArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeArgs {
    return new SwitchModeArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeArgs {
    return new SwitchModeArgs().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeArgs | PlainMessage<SwitchModeArgs> | undefined, b: SwitchModeArgs | PlainMessage<SwitchModeArgs> | undefined): boolean {
    return proto3.util.equals(SwitchModeArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeResult
 */
export class SwitchModeResult extends Message<SwitchModeResult> {
  /**
   * @generated from oneof agent.v1.SwitchModeResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.SwitchModeSuccess success = 1;
     */
    value: SwitchModeSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.SwitchModeError error = 2;
     */
    value: SwitchModeError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.SwitchModeRejected rejected = 3;
     */
    value: SwitchModeRejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<SwitchModeResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: SwitchModeSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: SwitchModeError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: SwitchModeRejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeResult {
    return new SwitchModeResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeResult {
    return new SwitchModeResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeResult {
    return new SwitchModeResult().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeResult | PlainMessage<SwitchModeResult> | undefined, b: SwitchModeResult | PlainMessage<SwitchModeResult> | undefined): boolean {
    return proto3.util.equals(SwitchModeResult, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeSuccess
 */
export class SwitchModeSuccess extends Message<SwitchModeSuccess> {
  /**
   * @generated from field: string from_mode_id = 1;
   */
  fromModeId = "";

  /**
   * @generated from field: string to_mode_id = 2;
   */
  toModeId = "";

  constructor(data?: PartialMessage<SwitchModeSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_mode_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "to_mode_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeSuccess {
    return new SwitchModeSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeSuccess {
    return new SwitchModeSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeSuccess {
    return new SwitchModeSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeSuccess | PlainMessage<SwitchModeSuccess> | undefined, b: SwitchModeSuccess | PlainMessage<SwitchModeSuccess> | undefined): boolean {
    return proto3.util.equals(SwitchModeSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeError
 */
export class SwitchModeError extends Message<SwitchModeError> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<SwitchModeError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeError {
    return new SwitchModeError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeError {
    return new SwitchModeError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeError {
    return new SwitchModeError().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeError | PlainMessage<SwitchModeError> | undefined, b: SwitchModeError | PlainMessage<SwitchModeError> | undefined): boolean {
    return proto3.util.equals(SwitchModeError, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeRejected
 */
export class SwitchModeRejected extends Message<SwitchModeRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<SwitchModeRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeRejected {
    return new SwitchModeRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeRejected {
    return new SwitchModeRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeRejected {
    return new SwitchModeRejected().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeRejected | PlainMessage<SwitchModeRejected> | undefined, b: SwitchModeRejected | PlainMessage<SwitchModeRejected> | undefined): boolean {
    return proto3.util.equals(SwitchModeRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeToolCall
 */
export class SwitchModeToolCall extends Message<SwitchModeToolCall> {
  /**
   * @generated from field: agent.v1.SwitchModeArgs args = 1;
   */
  args?: SwitchModeArgs;

  /**
   * @generated from field: agent.v1.SwitchModeResult result = 2;
   */
  result?: SwitchModeResult;

  constructor(data?: PartialMessage<SwitchModeToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: SwitchModeArgs },
    { no: 2, name: "result", kind: "message", T: SwitchModeResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeToolCall {
    return new SwitchModeToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeToolCall {
    return new SwitchModeToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeToolCall {
    return new SwitchModeToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeToolCall | PlainMessage<SwitchModeToolCall> | undefined, b: SwitchModeToolCall | PlainMessage<SwitchModeToolCall> | undefined): boolean {
    return proto3.util.equals(SwitchModeToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeRequestQuery
 */
export class SwitchModeRequestQuery extends Message<SwitchModeRequestQuery> {
  /**
   * @generated from field: agent.v1.SwitchModeArgs args = 1;
   */
  args?: SwitchModeArgs;

  constructor(data?: PartialMessage<SwitchModeRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: SwitchModeArgs },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeRequestQuery {
    return new SwitchModeRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeRequestQuery {
    return new SwitchModeRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeRequestQuery {
    return new SwitchModeRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeRequestQuery | PlainMessage<SwitchModeRequestQuery> | undefined, b: SwitchModeRequestQuery | PlainMessage<SwitchModeRequestQuery> | undefined): boolean {
    return proto3.util.equals(SwitchModeRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeRequestResponse
 */
export class SwitchModeRequestResponse extends Message<SwitchModeRequestResponse> {
  /**
   * @generated from oneof agent.v1.SwitchModeRequestResponse.result
   */
  result: {
    /**
     * @generated from field: agent.v1.SwitchModeRequestResponse_Approved approved = 1;
     */
    value: SwitchModeRequestResponse_Approved;
    case: "approved";
  } | {
    /**
     * @generated from field: agent.v1.SwitchModeRequestResponse_Rejected rejected = 2;
     */
    value: SwitchModeRequestResponse_Rejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<SwitchModeRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "approved", kind: "message", T: SwitchModeRequestResponse_Approved, oneof: "result" },
    { no: 2, name: "rejected", kind: "message", T: SwitchModeRequestResponse_Rejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeRequestResponse {
    return new SwitchModeRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse {
    return new SwitchModeRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse {
    return new SwitchModeRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeRequestResponse | PlainMessage<SwitchModeRequestResponse> | undefined, b: SwitchModeRequestResponse | PlainMessage<SwitchModeRequestResponse> | undefined): boolean {
    return proto3.util.equals(SwitchModeRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeRequestResponse_Approved
 */
export class SwitchModeRequestResponse_Approved extends Message<SwitchModeRequestResponse_Approved> {
  constructor(data?: PartialMessage<SwitchModeRequestResponse_Approved>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeRequestResponse_Approved";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeRequestResponse_Approved {
    return new SwitchModeRequestResponse_Approved().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse_Approved {
    return new SwitchModeRequestResponse_Approved().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse_Approved {
    return new SwitchModeRequestResponse_Approved().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeRequestResponse_Approved | PlainMessage<SwitchModeRequestResponse_Approved> | undefined, b: SwitchModeRequestResponse_Approved | PlainMessage<SwitchModeRequestResponse_Approved> | undefined): boolean {
    return proto3.util.equals(SwitchModeRequestResponse_Approved, a, b);
  }
}

/**
 * @generated from message agent.v1.SwitchModeRequestResponse_Rejected
 */
export class SwitchModeRequestResponse_Rejected extends Message<SwitchModeRequestResponse_Rejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<SwitchModeRequestResponse_Rejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.SwitchModeRequestResponse_Rejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SwitchModeRequestResponse_Rejected {
    return new SwitchModeRequestResponse_Rejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse_Rejected {
    return new SwitchModeRequestResponse_Rejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SwitchModeRequestResponse_Rejected {
    return new SwitchModeRequestResponse_Rejected().fromJsonString(jsonString, options);
  }

  static equals(a: SwitchModeRequestResponse_Rejected | PlainMessage<SwitchModeRequestResponse_Rejected> | undefined, b: SwitchModeRequestResponse_Rejected | PlainMessage<SwitchModeRequestResponse_Rejected> | undefined): boolean {
    return proto3.util.equals(SwitchModeRequestResponse_Rejected, a, b);
  }
}

