// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file agent/v1/web_fetch_tool.proto (package agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message agent.v1.WebFetchArgs
 */
export class WebFetchArgs extends Message<WebFetchArgs> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId = "";

  constructor(data?: PartialMessage<WebFetchArgs>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchArgs";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tool_call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchArgs {
    return new WebFetchArgs().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchArgs {
    return new WebFetchArgs().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchArgs {
    return new WebFetchArgs().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchArgs | PlainMessage<WebFetchArgs> | undefined, b: WebFetchArgs | PlainMessage<WebFetchArgs> | undefined): boolean {
    return proto3.util.equals(WebFetchArgs, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchSuccess
 */
export class WebFetchSuccess extends Message<WebFetchSuccess> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: string markdown = 2;
   */
  markdown = "";

  constructor(data?: PartialMessage<WebFetchSuccess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchSuccess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "markdown", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchSuccess {
    return new WebFetchSuccess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchSuccess {
    return new WebFetchSuccess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchSuccess {
    return new WebFetchSuccess().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchSuccess | PlainMessage<WebFetchSuccess> | undefined, b: WebFetchSuccess | PlainMessage<WebFetchSuccess> | undefined): boolean {
    return proto3.util.equals(WebFetchSuccess, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchError
 */
export class WebFetchError extends Message<WebFetchError> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<WebFetchError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchError {
    return new WebFetchError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchError {
    return new WebFetchError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchError {
    return new WebFetchError().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchError | PlainMessage<WebFetchError> | undefined, b: WebFetchError | PlainMessage<WebFetchError> | undefined): boolean {
    return proto3.util.equals(WebFetchError, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchRejected
 */
export class WebFetchRejected extends Message<WebFetchRejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<WebFetchRejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchRejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchRejected {
    return new WebFetchRejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchRejected {
    return new WebFetchRejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchRejected {
    return new WebFetchRejected().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchRejected | PlainMessage<WebFetchRejected> | undefined, b: WebFetchRejected | PlainMessage<WebFetchRejected> | undefined): boolean {
    return proto3.util.equals(WebFetchRejected, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchResult
 */
export class WebFetchResult extends Message<WebFetchResult> {
  /**
   * @generated from oneof agent.v1.WebFetchResult.result
   */
  result: {
    /**
     * @generated from field: agent.v1.WebFetchSuccess success = 1;
     */
    value: WebFetchSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: agent.v1.WebFetchError error = 2;
     */
    value: WebFetchError;
    case: "error";
  } | {
    /**
     * @generated from field: agent.v1.WebFetchRejected rejected = 3;
     */
    value: WebFetchRejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<WebFetchResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "message", T: WebFetchSuccess, oneof: "result" },
    { no: 2, name: "error", kind: "message", T: WebFetchError, oneof: "result" },
    { no: 3, name: "rejected", kind: "message", T: WebFetchRejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchResult {
    return new WebFetchResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchResult {
    return new WebFetchResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchResult {
    return new WebFetchResult().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchResult | PlainMessage<WebFetchResult> | undefined, b: WebFetchResult | PlainMessage<WebFetchResult> | undefined): boolean {
    return proto3.util.equals(WebFetchResult, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchToolCall
 */
export class WebFetchToolCall extends Message<WebFetchToolCall> {
  /**
   * @generated from field: agent.v1.WebFetchArgs args = 1;
   */
  args?: WebFetchArgs;

  /**
   * @generated from field: agent.v1.WebFetchResult result = 2;
   */
  result?: WebFetchResult;

  constructor(data?: PartialMessage<WebFetchToolCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchToolCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: WebFetchArgs },
    { no: 2, name: "result", kind: "message", T: WebFetchResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchToolCall {
    return new WebFetchToolCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchToolCall {
    return new WebFetchToolCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchToolCall {
    return new WebFetchToolCall().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchToolCall | PlainMessage<WebFetchToolCall> | undefined, b: WebFetchToolCall | PlainMessage<WebFetchToolCall> | undefined): boolean {
    return proto3.util.equals(WebFetchToolCall, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchRequestQuery
 */
export class WebFetchRequestQuery extends Message<WebFetchRequestQuery> {
  /**
   * @generated from field: agent.v1.WebFetchArgs args = 1;
   */
  args?: WebFetchArgs;

  constructor(data?: PartialMessage<WebFetchRequestQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchRequestQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "args", kind: "message", T: WebFetchArgs },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchRequestQuery {
    return new WebFetchRequestQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchRequestQuery {
    return new WebFetchRequestQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchRequestQuery {
    return new WebFetchRequestQuery().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchRequestQuery | PlainMessage<WebFetchRequestQuery> | undefined, b: WebFetchRequestQuery | PlainMessage<WebFetchRequestQuery> | undefined): boolean {
    return proto3.util.equals(WebFetchRequestQuery, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchRequestResponse
 */
export class WebFetchRequestResponse extends Message<WebFetchRequestResponse> {
  /**
   * @generated from oneof agent.v1.WebFetchRequestResponse.result
   */
  result: {
    /**
     * @generated from field: agent.v1.WebFetchRequestResponse.Approved approved = 1;
     */
    value: WebFetchRequestResponse_Approved;
    case: "approved";
  } | {
    /**
     * @generated from field: agent.v1.WebFetchRequestResponse.Rejected rejected = 2;
     */
    value: WebFetchRequestResponse_Rejected;
    case: "rejected";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<WebFetchRequestResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchRequestResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "approved", kind: "message", T: WebFetchRequestResponse_Approved, oneof: "result" },
    { no: 2, name: "rejected", kind: "message", T: WebFetchRequestResponse_Rejected, oneof: "result" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchRequestResponse {
    return new WebFetchRequestResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchRequestResponse {
    return new WebFetchRequestResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchRequestResponse {
    return new WebFetchRequestResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchRequestResponse | PlainMessage<WebFetchRequestResponse> | undefined, b: WebFetchRequestResponse | PlainMessage<WebFetchRequestResponse> | undefined): boolean {
    return proto3.util.equals(WebFetchRequestResponse, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchRequestResponse.Approved
 */
export class WebFetchRequestResponse_Approved extends Message<WebFetchRequestResponse_Approved> {
  constructor(data?: PartialMessage<WebFetchRequestResponse_Approved>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchRequestResponse.Approved";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchRequestResponse_Approved {
    return new WebFetchRequestResponse_Approved().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchRequestResponse_Approved {
    return new WebFetchRequestResponse_Approved().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchRequestResponse_Approved {
    return new WebFetchRequestResponse_Approved().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchRequestResponse_Approved | PlainMessage<WebFetchRequestResponse_Approved> | undefined, b: WebFetchRequestResponse_Approved | PlainMessage<WebFetchRequestResponse_Approved> | undefined): boolean {
    return proto3.util.equals(WebFetchRequestResponse_Approved, a, b);
  }
}

/**
 * @generated from message agent.v1.WebFetchRequestResponse.Rejected
 */
export class WebFetchRequestResponse_Rejected extends Message<WebFetchRequestResponse_Rejected> {
  /**
   * @generated from field: string reason = 1;
   */
  reason = "";

  constructor(data?: PartialMessage<WebFetchRequestResponse_Rejected>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "agent.v1.WebFetchRequestResponse.Rejected";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WebFetchRequestResponse_Rejected {
    return new WebFetchRequestResponse_Rejected().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WebFetchRequestResponse_Rejected {
    return new WebFetchRequestResponse_Rejected().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WebFetchRequestResponse_Rejected {
    return new WebFetchRequestResponse_Rejected().fromJsonString(jsonString, options);
  }

  static equals(a: WebFetchRequestResponse_Rejected | PlainMessage<WebFetchRequestResponse_Rejected> | undefined, b: WebFetchRequestResponse_Rejected | PlainMessage<WebFetchRequestResponse_Rejected> | undefined): boolean {
    return proto3.util.equals(WebFetchRequestResponse_Rejected, a, b);
  }
}

